<template>
  <div class="page">
    <header class="page-heading"><div><div class="hero-title"><h1>集群</h1><t-tag class="source-tag" variant="outline">LIVE + MOCK</t-tag></div><p>统一查看 EventMesh 集群、部署状态与关联资源；不可用指标不会使用模拟值冒充。</p></div><div class="page-heading-actions"><t-tag theme="warning" variant="outline">模拟操作</t-tag><t-button variant="outline" @click="deploy('script')"><CodeIcon />基于脚本部署</t-button><t-button variant="outline" @click="deploy('meta')"><DataBaseIcon />基于全量 Meta 集群部署</t-button><t-button theme="primary" @click="openCopy(rows[0])"><FileCopyIcon />复制集群</t-button></div></header>
    <MetricStrip :items="metrics" />
    <section v-if="activeTasks.length" class="panel task-panel"><div class="section-heading"><div><h2>集群任务</h2><p>完成后自动收起，结果保留在操作记录</p></div><t-tag>{{ activeTasks.length }} 个进行中</t-tag></div><div v-for="task in activeTasks" :key="task.id" class="task-row"><LoadingIcon /><div><strong>{{ task.sourceName }} → {{ task.targetName }}</strong><span>正在复制 {{ task.topicCount }} Topics、{{ task.consumerCount }} 消费者</span><t-progress :percentage="task.progress" size="small" /></div><b>{{ task.progress }}%</b></div></section>
    <section class="panel inventory-panel"><div class="section-heading"><div><h2>所有集群</h2><p>生命周期请求连接后端；复制、部署与导出使用前端模拟数据</p></div><div class="panel-actions"><t-input v-model="search" clearable placeholder="搜索集群名称或地域"><template #prefix-icon><SearchIcon /></template></t-input><t-button variant="outline" :loading="query.isFetching.value" @click="query.refetch()"><RefreshIcon />刷新 Live 数据</t-button></div></div>
      <PageState v-if="query.isLoading.value" type="loading" title="正在加载 Live 集群及节点" />
      <t-alert v-else-if="query.isError.value && !query.data.value" theme="error" title="首页集群接口连接失败" message="请确认后端服务和 MySQL 已启动。"><template #operation><t-button variant="text" @click="query.refetch()">重试</t-button></template></t-alert>
      <t-table v-else row-key="id" :data="filtered" :columns="columns" hover table-layout="auto" @row-click="({ row }) => open(row)">
        <template #cluster="{ row }"><span class="identity-cell"><ServerIcon /><span><strong>{{ row.name }} <t-tag size="small" :theme="row.isMock ? 'warning' : 'success'" variant="outline">{{ row.isMock ? 'MOCK' : 'LIVE' }}</t-tag></strong><small>{{ row.description }}</small></span></span></template>
        <template #deployStatus="{ row }"><StatusBadge :value="statusOf(row)" :label="statusLabel(row)" :code="statusOf(row)" /></template>
        <template #hosting="{ row }"><span><strong>{{ row.hostingType }}</strong><br><small class="muted">{{ row.hosting }} · {{ row.kubernetes }}</small></span></template>
        <template #nodes="{ row }"><strong>{{ row.runtimes ?? '—' }}</strong> Runtime<br><small class="muted">{{ row.metaNodes ?? '—' }} Meta</small></template>
        <template #resources><span class="muted">— 未接入</span></template><template #rates><span class="muted">— 未接入</span></template>
        <template #region="{ row }"><strong>{{ row.region }}</strong><br><small class="mono">v{{ row.version }}</small></template>
        <template #actions="{ row }"><div class="panel-actions" @click.stop><t-button variant="text" theme="primary" @click="open(row)">管理</t-button><t-button variant="text" @click="openCopy(row)">复制</t-button><t-button variant="text" @click="exportRow(row)">导出</t-button><t-dropdown :options="actionOptions(row)" @click="({ value }) => lifecycle(row, value)"><t-button variant="text">更多</t-button></t-dropdown></div></template>
      </t-table><PageState v-if="!query.isLoading.value && !filtered.length" type="empty" title="未找到匹配集群" />
    </section>
    <t-dialog v-model:visible="copyVisible" header="复制集群 · Mock" :confirm-btn="{ content: '开始复制', disabled: !copyName.trim() }" @confirm="confirmCopy"><div class="dialog-form"><div class="dialog-note">整集群复制会继承 Runtime、Meta、存储关联，并在完成后出现在集群列表。</div><label>源集群<t-input :value="copySource?.name" readonly /></label><label>目标集群名称<t-input v-model="copyName" /></label></div></t-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from "vue"; import { useRouter, useRoute } from "vue-router"; import { useQuery } from "@tanstack/vue-query"; import { DialogPlugin, MessagePlugin } from "tdesign-vue-next"; import { CodeIcon, DataBaseIcon, FileCopyIcon, LoadingIcon, RefreshIcon, SearchIcon, ServerIcon } from "tdesign-icons-vue-next";
import { dashboardRepository } from "../api/dashboardRepository"; import { submitClusterLifecycle } from "../api/clusterLifecycle"; import { mockClusters } from "../mock/mockClusterData"; import { mergeHomepageClusters, resolveHomepageDeployStatus } from "../data/homepageClusters"; import { isDeployStatus, lifecycleLabel, primaryLifecycleAction } from "../mock/mockLifecycle"; import MetricStrip from "../components/common/MetricStrip.vue"; import PageState from "../components/common/PageState.vue"; import StatusBadge from "../components/common/StatusBadge.vue"; import { useMockLifecycleStore } from "../stores/mockLifecycle"; import { useMockClusterStore } from "../stores/mockCluster"; import { useCopyTaskStore } from "../stores/copyTasks";
const router = useRouter(); const route = useRoute(); const lifecycleStore = useMockLifecycleStore(); const clusterStore = useMockClusterStore(); const copyStore = useCopyTaskStore(); const search = ref(String(route.query.search ?? "")); const copyVisible = ref(false); const copySource = ref<any>(null); const copyName = ref("");
const query = useQuery({ queryKey: ["dashboard", "homepage-clusters"], queryFn: () => dashboardRepository.getHomepageClusters(), retry: false });
const rows = computed(() => mergeHomepageClusters(query.data.value ?? [], mockClusters, copyStore.copiedClusters).all);
const filtered = computed(() => rows.value.filter((row: any) => `${row.name} ${row.region} ${row.description}`.toLowerCase().includes(search.value.toLowerCase())));
const activeTasks = computed(() => copyStore.tasks.filter((task: any) => task.progress < 100)); const timer = window.setInterval(() => copyStore.tick(), 1200); onBeforeUnmount(() => clearInterval(timer));
const metrics = computed(() => { const live = rows.value.filter((item: any) => !item.isMock); const runtimeValues = live.map((item: any) => item.runtimes).filter(Number.isFinite); return [{ label: "集群总数 · Live", value: query.isLoading.value ? "—" : live.length, note: copyStore.copiedClusters.length ? `${copyStore.copiedClusters.length} 个 Mock` : "后端已确认" }, { label: "Runtime 节点 · Live", value: runtimeValues.length ? runtimeValues.reduce((a: number,b: number)=>a+b,0) : "—", note: `已获取 ${runtimeValues.length}/${live.length} 个集群` }, { label: "平均 CPU · 未接入", value: "—", note: "暂无可用接口" }, { label: "平均内存 · 未接入", value: "—", note: "暂无可用接口" }, { label: "消息速率 · 未接入", value: "—", note: "报表接口尚不可用" }]; });
const columns = [{ colKey: "cluster", title: "集群", width: 260 }, { colKey: "deployStatus", title: "部署状态", width: 165 }, { colKey: "hosting", title: "托管方式", width: 190 }, { colKey: "nodes", title: "节点 · Live", width: 110 }, { colKey: "resources", title: "资源使用率", width: 110 }, { colKey: "rates", title: "MQ 速率", width: 100 }, { colKey: "region", title: "地域 / 版本", width: 150 }, { colKey: "actions", title: "操作", width: 210, fixed: "right" }];
function open(row: any) { router.push(`/clusters/${encodeURIComponent(row.mockRouteId ?? row.id)}/overview`); }
function statusOf(row: any) { return resolveHomepageDeployStatus(row, lifecycleStore.statuses).value; } function statusLabel(row: any) { const value = statusOf(row); return isDeployStatus(value) ? lifecycleLabel(value) : "未知"; }
function actionOptions(row: any) { const value = statusOf(row); const primary = isDeployStatus(value) ? primaryLifecycleAction(value) : null; return [...(primary ? [{ content: ({start:"启动",pause:"暂停",resume:"恢复"} as any)[primary], value: primary }] : []), { content: "注销", value: "uninstall", theme: "error" }]; }
function lifecycle(row: any, action: any) { const content = action === "uninstall" ? `注销 ${row.name}？该操作需要明确确认。` : `确认对 ${row.name} 执行该生命周期操作？`; DialogPlugin.confirm({ header: action === "uninstall" ? "危险操作确认" : "确认操作", body: content, theme: action === "uninstall" ? "danger" : "default", confirmBtn: action === "uninstall" ? "确认注销" : "确认", onConfirm: async () => { try { if (row.isMock) lifecycleStore.perform({ kind: "cluster", id: row.id, name: row.name, action, currentStatus: statusOf(row) }); else await submitClusterLifecycle(row.id, action); MessagePlugin.success("操作已提交"); await query.refetch(); } catch (error: any) { MessagePlugin.error(error?.message ?? "操作失败"); } } }); }
function openCopy(row: any) { if (!row) return; copySource.value = row; copyName.value = `${row.name}-copy`; copyVisible.value = true; }
function confirmCopy() { const task = copyStore.create(copySource.value, copyName.value); clusterStore.inheritRelations(copySource.value.mockRouteId ?? copySource.value.id, task.targetId); copyVisible.value = false; MessagePlugin.success("复制任务已创建"); }
function exportRow(row: any) { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), cluster: row }, null, 2)], { type: "application/json" }); const href = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = href; link.download = `${row.id}-cluster-export.json`; link.click(); URL.revokeObjectURL(href); }
function deploy(mode: string) { const source = rows.value[0]; if (!source) return; openCopy(source); copyName.value = mode === "meta" ? "codex-sim-meta-deployed" : "codex-sim-script-deployed"; }
</script>

<style scoped>.inventory-panel{min-height:480px}.task-panel{margin-bottom:14px}.task-row{display:grid;grid-template-columns:24px minmax(0,1fr) 45px;align-items:center;gap:12px;padding:12px 16px;border-bottom:1px solid #e5edf5}.task-row>svg{color:#225aa0;animation:spin 1s linear infinite}.task-row>div{display:grid;gap:5px}.task-row span{font-size:11px;color:#71869b}</style>
