<template><div class="page"><PageState v-if="mainQuery.isLoading.value" type="loading" title="正在加载集群" /><PageState v-else-if="mainQuery.isError.value" type="error" title="集群加载失败" :description="String(mainQuery.error.value?.message ?? '')" :retry="mainQuery.refetch" /><template v-else>
  <section v-if="showHero" class="hero"><div><button class="hero-path" @click="router.push('/clusters')">返回全部集群 /</button><div class="hero-title"><h1>{{ cluster.name }}</h1><StatusBadge :value="cluster.deployStatus ?? cluster.status" :label="deployLabel" :code="cluster.deployStatus"/><t-tag class="source-tag" variant="outline">{{ sourceLabel }}</t-tag></div><p>{{ cluster.description }}</p><div class="hero-meta"><span>版本 {{ cluster.version }}</span><span>{{ cluster.region }}</span><span>集群 ID {{ cluster.id }}</span></div></div><div class="hero-actions"><t-tag theme="warning" variant="outline">操作 · Mock</t-tag><t-button variant="outline" @click="copyCluster">复制集群</t-button><t-button theme="primary" @click="createNodeVisible=true">添加节点</t-button></div></section>
  <t-alert v-if="warnings.length" theme="warning" title="部分数据暂不可用" :message="warnings.join('；')" class="module-alert" />
  <template v-if="view==='summary'"><MetricStrip :items="summaryMetrics"/><div class="overview-grid three"><section v-for="card in landscapeCards" :key="card.label" class="panel summary-card"><h2>{{card.label}}</h2><p>{{card.note}}</p><strong class="large-value">{{card.value}}</strong><t-button variant="text" theme="primary" @click="go(card.view,card.section)">查看详情</t-button></section></div></template>
  <template v-else-if="view==='overview'"><MetricStrip :items="overviewMetrics"/><div class="overview-grid"><section class="panel"><div class="section-heading"><div><h2>消息处理趋势 · Mock</h2><p>后端暂无稳定时序指标接口</p></div><t-tag variant="outline">ANTV G2</t-tag></div><TrendChart :input="trendInput"/></section><section class="panel summary-card"><h2>集群信息</h2><p>当前 EventMesh 的部署与托管信息</p><dl class="fact-list"><div><dt>集群类型</dt><dd>{{cluster.clusterType}}</dd></div><div><dt>托管方式</dt><dd>{{cluster.trusteeshipType??'—'}}</dd></div><div><dt>云平台</dt><dd>{{cluster.cloudProvider??'—'}}</dd></div><div><dt>Kubernetes</dt><dd>{{cluster.kubernetesCluster??'—'}}</dd></div><div><dt>运行时长</dt><dd>{{cluster.uptime??'—'}}</dd></div></dl></section></div></template>
  <TopologyView v-else-if="view==='topology'" :cluster="cluster" :components="components" :runtimes="runtimes" :topics="topics" :groups="groups" />
  <template v-else-if="view==='relations'"><DataPanel title="EventMesh 关联集群" description="EventMesh 主动关联 Runtime 与存储；Meta 关系由 Meta 集群发起" :data="relationRows" :columns="relationColumns"><template #toolbar><t-button theme="primary" @click="relationVisible=true"><LinkIcon/>关联集群 · Mock</t-button></template><template #name="{row}"><span class="identity-cell"><ServerIcon/><span><strong>{{row.name}}</strong><small>{{row.description}}</small></span></span></template><template #status="{row}"><StatusBadge :value="row.status" /></template><template #actions="{row}"><t-button variant="text" theme="danger" @click="removeRelation(row)">解除</t-button></template></DataPanel></template>
  <template v-else-if="['runtime','meta','storage'].includes(view)"><ModulePage :kind="view" :section="section" :cluster-id="clusterId" :live="moduleData" /></template>
  <template v-else-if="view==='topics'"><MetricStrip :items="topicMetrics"/><section v-if="section==='overview'" class="overview-grid"><section class="panel"><div class="section-heading"><div><h2>Topic 吞吐趋势 · Mock</h2><p>Topic 总数与队列来自后端，吞吐时序暂未接入</p></div></div><TrendChart :input="trendInput"/></section><section class="panel summary-card"><h2>容量摘要</h2><p>EventMesh-facing Topic 与物理存储 Topic 保持语义分离。</p><dl class="fact-list"><div><dt>业务 Topic</dt><dd>{{topicRows.length}}</dd></div><div><dt>队列总数</dt><dd>{{moduleData?.data?.queueCount??'—'}}</dd></div><div><dt>关联存储</dt><dd>{{components.filter((x:any)=>['kafka','rocketmq'].includes(x.type)).length}}</dd></div></dl><t-button theme="primary" @click="resourceDialog='topic'">创建 Topic · Mock</t-button></section></section><DataPanel v-else title="Topic 列表" description="EventMesh-facing 业务 Topic；创建时同步写入选定存储集群的物理 Topic" :data="topicRows" :columns="topicColumns"><template #toolbar><t-button theme="primary" @click="resourceDialog='topic'">创建 Topic · Mock</t-button></template><template #status="{row}"><StatusBadge :value="row.status??'unknown'"/></template></DataPanel></template>
  <template v-else-if="view==='connections'"><MetricStrip :items="connectionMetrics"/><DataPanel v-if="section==='list'" title="客户端连接" description="客户端到 Runtime 的连接视图；不可用字段明确标记" :data="connectionRows" :columns="connectionColumns"><template #status="{row}"><StatusBadge :value="row.status"/></template></DataPanel><div v-else class="overview-grid"><section class="panel"><div class="section-heading"><div><h2>连接趋势 · Mock</h2><p>后端暂无稳定连接时序接口</p></div></div><TrendChart :input="trendInput"/></section><section class="panel summary-card"><h2>连接分布</h2><p>当前连接信息由可用 Runtime 资源汇总。</p><dl class="fact-list"><div><dt>Runtime</dt><dd>{{runtimes.length}}</dd></div><div><dt>协议</dt><dd>HTTP · TCP · MQTT</dd></div><div><dt>健康检查</dt><dd>未接入</dd></div></dl></section></div></template>
  <template v-else-if="view==='consumers'"><MetricStrip :items="consumerMetrics"/><DataPanel title="Consumer Groups" description="消费组及 Topic 订阅来自可用后端查询" :data="consumerRows" :columns="consumerColumns"><template #toolbar><t-button theme="primary" @click="resourceDialog='consumer'">创建消费组 · Mock</t-button></template><template #status="{row}"><StatusBadge :value="row.status??'unknown'"/></template></DataPanel></template>
  <template v-else-if="view==='operations'"><DataPanel title="操作记录" description="后端操作记录与前端模拟生命周期、复制任务统一展示" :data="operationRows" :columns="operationColumns"><template #status="{row}"><StatusBadge :value="row.state??row.result" :label="row.state??row.result"/></template></DataPanel></template>
  <template v-else-if="view==='configuration'"><DataPanel title="只读配置" description="当前后端写配置能力未完成，因此保持只读" :data="configRows" :columns="configColumns" :searchable="true" /></template>
  <t-dialog v-model:visible="createNodeVisible" header="添加集群节点 · Mock" :confirm-btn="{content:'添加节点',disabled:!nodeName.trim()}" @confirm="addNode"><div class="dialog-form"><div class="dialog-note">节点名称强制使用 codex-sim- 前缀，数据仅保存在浏览器。</div><label>节点角色<t-select v-model="nodeRole" :options="[{label:'Runtime 节点',value:'Runtime'},{label:'Meta 节点',value:'Meta'}]" /></label><label>节点名称<t-input v-model="nodeName" /></label></div></t-dialog>
  <t-dialog v-model:visible="relationVisible" header="关联组件集群 · Mock" @confirm="addRelations"><div class="relation-grid"><label v-for="item in availableRelations" :key="item.id" class="relation-option"><t-checkbox v-model="relationSelection" :value="item.id"/><span><strong>{{item.name}}</strong><br><small class="muted">{{item.type}} · {{item.region}}</small></span></label></div></t-dialog>
  <t-dialog :visible="Boolean(resourceDialog)" :header="resourceDialog==='topic'?'创建 Topic · Mock':'创建消费组 · Mock'" @close="resourceDialog=null" @confirm="createResource"><div class="dialog-form"><div class="dialog-note">该写操作仅保存在前端 Mock 数据中。</div><label>名称<t-input v-model="resourceName" /></label><label v-if="resourceDialog==='topic'">存储目标<t-select v-model="storageTarget" :options="storageOptions" /></label></div></t-dialog>
</template></div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue"; import { useRoute, useRouter } from "vue-router"; import { useQuery } from "@tanstack/vue-query"; import { MessagePlugin } from "tdesign-vue-next"; import { LinkIcon, ServerIcon } from "tdesign-icons-vue-next";
import { dashboardRepository } from "../api/dashboardRepository"; import { mockClusters, mockMessageSeries } from "../mock/mockClusterData"; import { mockComponentClusters } from "../mock/mockClusterRelations"; import { ensureSimName } from "../mock/mockWritableResources"; import { isDeployStatus, lifecycleLabel } from "../mock/mockLifecycle"; import { useMockClusterStore } from "../stores/mockCluster"; import { useMockLifecycleStore } from "../stores/mockLifecycle"; import { useCopyTaskStore } from "../stores/copyTasks"; import MetricStrip from "../components/common/MetricStrip.vue"; import StatusBadge from "../components/common/StatusBadge.vue"; import PageState from "../components/common/PageState.vue"; import DataPanel from "../components/common/DataPanel.vue"; import TrendChart from "../components/charts/TrendChart.vue"; import TopologyView from "../topology/TopologyView.vue"; import ModulePage from "../components/modules/ModulePage.vue";
const route=useRoute(),router=useRouter(),mockStore=useMockClusterStore(),lifecycleStore=useMockLifecycleStore(),copyStore=useCopyTaskStore(); const clusterId=computed(()=>String(route.params.clusterId)); const view=computed(()=>String(route.params.view||"overview")); const section=computed(()=>String(route.query.section||"overview"));
function mockOverview(id:string){const item=[...mockClusters,...copyStore.copiedClusters].find((x:any)=>x.id===id||x.name===id);if(!item)throw new Error(`未找到集群 ${id}`);const relations=mockStore.relations.filter((x:any)=>x.eventMeshClusterId===id);const components=mockComponentClusters.filter((x:any)=>relations.some((r:any)=>r.componentClusterId===x.id));return {data:{cluster:{...item,deployStatus:lifecycleStore.statusOf("cluster",item.id),clusterType:"EVENTMESH_JVM_CLUSTER"},components,runtimes:components.filter((x:any)=>x.type==="runtime").flatMap((x:any)=>x.nodes),topics:(item.topics??[]).map((name:string,index:number)=>({id:`topic-${index}`,name,status:"healthy",partitions:12})),groups:(item.consumers??[]).map((name:string,index:number)=>({id:`group-${index}`,name,status:"healthy"})),availability:{runtimes:true,topology:true,topics:true,groups:true}},meta:{source:"mock",warnings:[],fetchedAt:new Date().toISOString()}}}
const mainQuery=useQuery({queryKey:computed(()=>["eventmesh-overview",clusterId.value]),queryFn:async()=>{try{return await dashboardRepository.getEventMeshOverview(clusterId.value)}catch(error){if([...mockClusters,...copyStore.copiedClusters].some((x:any)=>x.id===clusterId.value||x.name===clusterId.value))return mockOverview(clusterId.value);throw error}},retry:false});
const moduleQuery=useQuery({queryKey:computed(()=>["cluster-module",clusterId.value,view.value,section.value]),queryFn:()=>{if(view.value==="meta")return section.value==="clusters"?dashboardRepository.getMetaClusterList(clusterId.value):dashboardRepository.getMetaOverview(clusterId.value);if(view.value==="storage")return section.value==="kafka"?dashboardRepository.getKafkaClusterList(clusterId.value):section.value==="rocketmq"?dashboardRepository.getRocketMqClusterList(clusterId.value):dashboardRepository.getStorageOverview(clusterId.value);if(view.value==="runtime")return dashboardRepository.getEventMeshRuntimes(clusterId.value);if(view.value==="topics")return dashboardRepository.getTopicOverview(clusterId.value);if(view.value==="consumers")return dashboardRepository.getConsumerGroups(clusterId.value);if(view.value==="operations")return dashboardRepository.getOperationHistory(clusterId.value);return Promise.resolve(null)},enabled:computed(()=>["runtime","meta","storage","topics","consumers","operations"].includes(view.value)),retry:false});
const payload=computed(()=>mainQuery.data.value?.data??{}),cluster=computed(()=>payload.value.cluster??{}),components=computed(()=>payload.value.components??[]),runtimes=computed(()=>payload.value.runtimes??[]),topics=computed(()=>payload.value.topics??[]),groups=computed(()=>payload.value.groups??[]),warnings=computed(()=>[...(mainQuery.data.value?.meta?.warnings??[]),...(moduleQuery.data.value?.meta?.warnings??[])]),moduleData=computed(()=>moduleQuery.data.value),showHero=computed(()=>["summary","overview","topology","relations"].includes(view.value));
const sourceLabel=computed(()=>mainQuery.data.value?.meta?.source==="mock"?"MOCK DATA":warnings.value.length?"PARTIAL LIVE":"LIVE DATA");const deployLabel=computed(()=>isDeployStatus(cluster.value.deployStatus)?lifecycleLabel(cluster.value.deployStatus):cluster.value.status??"未知");
const overviewMetrics=computed(()=>[{label:"Runtime",value:runtimes.value.length,note:"实例"},{label:"关联组件",value:components.value.length,note:"Runtime / Meta / Storage"},{label:"Topics",value:topics.value.length,note:"业务主题"},{label:"Consumer",value:groups.value.length,note:"消费组"},{label:"配置",value:"只读",note:"写接口未完成"}]);const summaryMetrics=overviewMetrics;
const landscapeCards=computed(()=>[{label:"EventMesh 集群",value:1,note:"当前消息接入与路由根集群",view:"overview"},{label:"Runtime 集群",value:components.value.filter((x:any)=>x.type==="runtime").length,note:"独立管理的运行时集群",view:"runtime",section:"clusters"},{label:"Meta 集群",value:components.value.filter((x:any)=>x.type==="meta").length,note:"主动关联 EventMesh",view:"meta",section:"clusters"},{label:"Kafka 存储",value:components.value.filter((x:any)=>x.type==="kafka").length,note:"KRaft 存储集群",view:"storage",section:"kafka"},{label:"RocketMQ 存储",value:components.value.filter((x:any)=>x.type==="rocketmq").length,note:"NameServer 与 Broker Group",view:"storage",section:"rocketmq"}]);
const trendInput=computed(()=>({points:mockMessageSeries.labels.flatMap((time:string,i:number)=>[{time,series:"流入",value:mockMessageSeries.inbound[i]},{time,series:"流出",value:mockMessageSeries.outbound[i]}]),unit:"K/s",source:"mock" as const,status:"ready" as const}));function go(v:string,s?:string){router.push({path:`/clusters/${encodeURIComponent(clusterId.value)}/${v}`,query:s&&s!=="overview"?{section:s}:{}})}
const relationVisible=ref(false),relationSelection=ref<string[]>([]);const relationRows=computed(()=>{const ids=new Set(mockStore.relations.filter((x:any)=>x.eventMeshClusterId===clusterId.value&&x.componentType!=="meta").map((x:any)=>x.componentClusterId));return mockComponentClusters.filter((x:any)=>ids.has(x.id)).map((x:any)=>({...x,direction:`EventMesh → ${x.type}`}))});const availableRelations=computed(()=>mockComponentClusters.filter((x:any)=>x.type!=="meta"&&!relationRows.value.some((r:any)=>r.id===x.id)));const relationColumns=[{colKey:"name",title:"组件集群"},{colKey:"type",title:"类型"},{colKey:"direction",title:"关系方向"},{colKey:"status",title:"状态"},{colKey:"actions",title:"操作",width:100}];function addRelations(){mockStore.addRelations(clusterId.value,relationSelection.value);relationSelection.value=[];relationVisible.value=false;MessagePlugin.success("已建立 Mock 关联")};function removeRelation(row:any){const rel=mockStore.relations.find((x:any)=>x.eventMeshClusterId===clusterId.value&&x.componentClusterId===row.id);if(rel)mockStore.removeRelation(rel.id)}
const topicRows=computed(()=>[...(moduleQuery.data.value?.data?.topics??topics.value),...mockStore.resources.topics.filter((x:any)=>x.eventMeshClusterId===clusterId.value)]);const topicMetrics=computed(()=>[{label:"Topic 总数",value:topicRows.value.length,note:"Live + Mock"},{label:"队列总数",value:moduleQuery.data.value?.data?.queueCount??"—",note:"Live"},{label:"写入速率",value:"—",note:"未接入"},{label:"消费速率",value:"—",note:"未接入"},{label:"异常 Topic",value:"—",note:"无健康接口"}]);const topicColumns=[{colKey:"name",title:"Topic"},{colKey:"partitions",title:"队列 / 分区"},{colKey:"replicas",title:"副本"},{colKey:"status",title:"状态"},{colKey:"createdAt",title:"创建时间"}];
const connectionRows=computed(()=>runtimes.value.map((x:any,i:number)=>({id:x.id??i,name:`client-${i+1}`,protocol:["HTTP","TCP","MQTT"][i%3],runtime:x.name??x.id,address:x.address??(x.host?`${x.host}:${x.port}`:"—"),status:x.status??"unknown"})));const connectionMetrics=computed(()=>[{label:"Runtime",value:runtimes.value.length,note:"连接入口"},{label:"客户端",value:connectionRows.value.length,note:"可确认记录"},{label:"活跃连接",value:"—",note:"未接入"},{label:"P99 延迟",value:"—",note:"未接入"},{label:"异常连接",value:"—",note:"无健康接口"}]);const connectionColumns=[{colKey:"name",title:"客户端"},{colKey:"protocol",title:"协议"},{colKey:"runtime",title:"Runtime"},{colKey:"address",title:"地址"},{colKey:"status",title:"状态"}];
const consumerRows=computed(()=>[...(moduleQuery.data.value?.data?.groups??groups.value),...mockStore.resources.consumers.filter((x:any)=>x.eventMeshClusterId===clusterId.value)]);const consumerMetrics=computed(()=>[{label:"消费组",value:consumerRows.value.length,note:"Live + Mock"},{label:"订阅 Topic",value:new Set(consumerRows.value.flatMap((x:any)=>x.topics??[])).size,note:"已确认"},{label:"消费速率",value:"—",note:"未接入"},{label:"积压",value:"—",note:"未接入"},{label:"异常组",value:"—",note:"无健康接口"}]);const consumerColumns=[{colKey:"name",title:"消费组"},{colKey:"topics",title:"订阅 Topic"},{colKey:"databaseStatus",title:"数据库状态"},{colKey:"createTime",title:"创建时间"},{colKey:"status",title:"健康"}];
const operationRows=computed(()=>[...(moduleQuery.data.value?.data?.operations??[]),...lifecycleStore.operations,...copyStore.tasks.map((x:any)=>({id:x.id,operationType:"COPY",content:`${x.sourceName} → ${x.targetName}`,state:x.progress>=100?"SUCCESS":"RUNNING",createTime:x.createdAt,result:`${x.progress}%`}))]);const operationColumns=[{colKey:"createTime",title:"时间"},{colKey:"operationType",title:"操作类型"},{colKey:"content",title:"详情"},{colKey:"operationUser",title:"操作人"},{colKey:"status",title:"状态"},{colKey:"result",title:"结果"}];const configRows=computed(()=>Object.entries(cluster.value.raw?.config??{}).map(([key,value],i)=>({id:i,key,value:String(value)})));const configColumns=[{colKey:"key",title:"配置项"},{colKey:"value",title:"值"}];
const createNodeVisible=ref(false),nodeRole=ref("Runtime"),nodeName=ref("codex-sim-runtime-new-01");function addNode(){const name=ensureSimName(nodeName.value,"codex-sim-runtime-new-01");mockStore.addNode({id:name,clusterId:clusterId.value,name,role:nodeRole.value,address:"待分配",status:"unknown",createdAt:new Date().toISOString()});createNodeVisible.value=false;MessagePlugin.success("模拟节点已添加")};function copyCluster(){router.push("/clusters")}
const resourceDialog=ref<"topic"|"consumer"|null>(null),resourceName=ref("codex-sim-new-resource"),storageTarget=ref("");const storageOptions=computed(()=>components.value.filter((x:any)=>["kafka","rocketmq"].includes(x.type)).map((x:any)=>({label:x.name,value:x.id})));watch(storageOptions,(items)=>{if(!storageTarget.value&&items[0])storageTarget.value=items[0].value},{immediate:true});function createResource(){const name=ensureSimName(resourceName.value,"codex-sim-resource");if(resourceDialog.value==="topic")mockStore.addTopic({id:`topic-${Date.now()}`,eventMeshClusterId:clusterId.value,storageClusterId:storageTarget.value,engine:components.value.find((x:any)=>x.id===storageTarget.value)?.type??"kafka",name,partitions:12,replicas:3,status:"healthy",createdAt:new Date().toISOString()});else mockStore.addConsumer({id:`consumer-${Date.now()}`,eventMeshClusterId:clusterId.value,name,topics:[],status:"healthy",createdAt:new Date().toISOString()});resourceDialog.value=null;MessagePlugin.success("模拟资源已创建")}
</script>
<style scoped>.module-alert{margin-bottom:12px}.large-value{display:block;font-size:32px;margin:18px 0;color:#203247}.summary-card .t-button{margin-top:18px}.overview-grid{margin-bottom:12px}</style>
