import { useEffect, useMemo, useState } from "react";
import { ApartmentOutlined, CheckCircleOutlined, CloudServerOutlined, ClusterOutlined, CopyOutlined, DashboardOutlined, DatabaseOutlined, DeleteOutlined, ExclamationCircleOutlined, HddOutlined, LinkOutlined, PlusOutlined, ReloadOutlined, SearchOutlined, TeamOutlined } from "@ant-design/icons";
import { App as AntApp, Button, Checkbox, Input, Modal, Select, Tag } from "antd";
import ReactECharts from "echarts-for-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { mockClusters, mockMessageSeries } from "../mock/mockClusterData";
import { mockComponentClusters } from "../mock/mockClusterRelations";
import { TopologyExperience } from "../topology/TopologyExperience";
import { componentClusterConsolePath, storageClusterConsolePath } from "../routes";
import { CreateConsumerModal, CreateTopicModal } from "../components/MockResourceCreateModals";
import { COMPONENT_TYPE_LABELS } from "../config/clusterDefinitions";
import { ResourceTable } from "../components/ResourceTable";
import { StatusBadge } from "../components/StatusBadge";
import { useMockRelations, useMockWritableResources } from "../store/mockClusterStore";

const MockTag = () => <Tag className="mock-source-tag">MOCK DATA</Tag>;
const Status = StatusBadge;
function UsageBar({ label, value }) { const tone=value>=80?"critical":value>=70?"warning":"normal"; return <div className="usage-row"><span>{label}</span><div><i className={tone} style={{width:`${value}%`}}/></div><strong>{value}%</strong></div>; }
const formatRate=(value)=>value>=1000?`${(value/1000).toFixed(1)}K/s`:`${value}/s`;
const componentTypeCopy=COMPONENT_TYPE_LABELS;

const copyStateKey="eventmesh-mock-copy-state-v2";
const emptyCopyState={tasks:[],copiedClusters:[]};
function readCopyState(){ if(typeof window==="undefined")return emptyCopyState; try{ const saved=JSON.parse(window.localStorage.getItem(copyStateKey)||"null"); return saved&&Array.isArray(saved.tasks)&&Array.isArray(saved.copiedClusters)?saved:emptyCopyState; }catch{return emptyCopyState;} }
function writeCopyState(state){ if(typeof window!=="undefined")window.localStorage.setItem(copyStateKey,JSON.stringify(state)); }
function copiedClusterFromTask(task){ return {...task.sourceSnapshot,id:task.targetId,name:task.targetName,description:`从 ${task.sourceName} 复制创建的集群`,status:"healthy",uptime:"刚刚创建",cpu:0,memory:0,storage:0,inRate:0,outRate:0,topics:task.topics,consumers:task.consumers}; }

function useCopyTasks() {
  const [copyState,setCopyState]=useState(readCopyState);
  useEffect(()=>{ const timer=window.setInterval(()=>setCopyState((current)=>{ let changed=false; const tasks=current.tasks.map((task)=>{ if(task.progress>=100)return task; changed=true; return {...task,progress:Math.min(100,task.progress+8)}; }); const copiedClusters=[...current.copiedClusters]; tasks.forEach((task)=>{ if(task.progress>=100&&!copiedClusters.some((cluster)=>cluster.id===task.targetId)){copiedClusters.unshift(copiedClusterFromTask(task));changed=true;} }); if(!changed)return current; const next={tasks,copiedClusters}; writeCopyState(next); return next; }),1200); return()=>window.clearInterval(timer); },[]);
  const createCopyTask=({source,targetName,topics,consumers})=>{ const stamp=Date.now(); const safeName=targetName.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"")||"eventmesh-copy"; const existingIds=new Set([...mockClusters,...copyState.copiedClusters].map((cluster)=>cluster.id)); const targetId=existingIds.has(safeName)?`${safeName}-${String(stamp).slice(-5)}`:safeName; const task={id:`copy-${stamp}`,targetId,createdAt:new Date().toISOString(),progress:8,sourceName:source.name,targetName:targetName.trim(),topicCount:topics.length,consumerCount:consumers.length,runtimes:source.runtimes,metaNodes:source.metaNodes,topics:[...topics],consumers:[...consumers],sourceSnapshot:{...source}}; setCopyState((current)=>{ const next={...current,tasks:[task,...current.tasks]}; writeCopyState(next); return next; }); return task; };
  return {tasks:copyState.tasks,copiedClusters:copyState.copiedClusters,clusters:[...mockClusters,...copyState.copiedClusters],createCopyTask};
}

function copyTaskPhase(progress){ if(progress>=100)return "复制完成"; if(progress>=82)return "初始化目标集群"; if(progress>=52)return "复制 Topic 与消费者"; if(progress>=24)return "复制 Runtime 与 Meta"; return "校验集群配置"; }

function CopyTaskPanel({tasks}) {
  const activeTasks=tasks.filter((task)=>task.progress<100);
  if(!activeTasks.length)return null;
  return <section className="panel mock-copy-task-panel"><div className="mock-copy-task-heading"><div><h2>集群复制任务</h2><p>完成后自动收起，可在操作历史中查看结果</p></div><span>{activeTasks.length} 个进行中</span></div><div className="mock-copy-task-list">{activeTasks.map((task)=><article key={task.id}><div className="mock-copy-task-icon running"><ReloadOutlined spin/></div><div className="mock-copy-task-main"><div><strong>{task.targetName}</strong><span>{task.sourceName} → {task.targetName}</span></div><div className="mock-copy-task-meta"><span>{copyTaskPhase(task.progress)}</span><span>{task.topicCount} Topics</span><span>{task.consumerCount} 消费者</span><span>{task.runtimes} Runtime · {task.metaNodes} Meta</span></div><div className="mock-copy-progress"><i style={{transform:`scaleX(${task.progress/100})`}}/></div></div><div className="mock-copy-task-state"><strong>{task.progress}%</strong><span>进行中</span></div></article>)}</div></section>;
}

function ClusterCopyModal({ open, sourceId, onClose, onCreate, clusters=mockClusters }) {
  const { message }=AntApp.useApp();
  const initial=clusters.find((cluster)=>cluster.id===sourceId)??clusters[0];
  const [selectedId,setSelectedId]=useState(initial.id); const selected=clusters.find((cluster)=>cluster.id===selectedId)??initial;
  const [name,setName]=useState(`${initial.name}-copy`); const [topics,setTopics]=useState(initial.topics); const [consumers,setConsumers]=useState(initial.consumers);
  const reset=(id)=>{ const next=clusters.find((cluster)=>cluster.id===id)??initial; setSelectedId(id); setName(`${next.name}-copy`); setTopics(next.topics); setConsumers(next.consumers); };
  useEffect(()=>{ if(open&&sourceId) reset(sourceId); },[open,sourceId]);
  const submit=()=>{ onCreate?.({source:selected,targetName:name,topics,consumers}); message.success(`已创建复制任务：${name}`); onClose(); };
  return <Modal className="cluster-copy-modal" width={760} title="复制整个集群" open={open} onCancel={onClose} onOk={submit} okText="开始复制" cancelText="取消" okButtonProps={{disabled:!name.trim()}}>
    <div className="mock-flow-note"><CopyOutlined/><div><strong>以集群为单位复制</strong><span>复制 Runtime 与 Meta 集群结构，并可选择随集群复制的 Topic 和消费者。这里不会生成单独的 Topic 或消费者副本。</span></div></div>
    <div className="copy-form-grid"><label>源集群<Select value={selected.id} onChange={reset} options={clusters.map((cluster)=>({value:cluster.id,label:cluster.name}))}/></label><label>新集群名称<Input value={name} onChange={(event)=>setName(event.target.value)}/></label></div>
    <div className="copy-resource-columns"><section><div><strong>选择 Topic</strong><span>{topics.length} / {selected.topics.length}</span></div><Checkbox.Group value={topics} onChange={setTopics} options={selected.topics}/></section><section><div><strong>选择消费者</strong><span>{consumers.length} / {selected.consumers.length}</span></div><Checkbox.Group value={consumers} onChange={setConsumers} options={selected.consumers}/></section></div>
    <div className="copy-summary"><span>目标托管：{selected.hosting}</span><span>Runtime：{selected.runtimes} 个</span><span>Meta：{selected.metaNodes} 个</span></div>
  </Modal>;
}

export function MockClusterOverview() {
  const navigate=useNavigate(); const [query,setQuery]=useState(""); const [hosting,setHosting]=useState("all"); const [copyId,setCopyId]=useState(null);
  const {tasks:copyTasks,clusters,createCopyTask}=useCopyTasks();
  const {inheritRelations}=useMockRelations();
  const startCopyTask=(payload)=>{const task=createCopyTask(payload);inheritRelations(payload.source.id,task.targetId);};
  const filtered=clusters.filter((cluster)=>`${cluster.name} ${cluster.region} ${cluster.description}`.toLowerCase().includes(query.toLowerCase())&&(hosting==="all"||cluster.hostingType===hosting));
  const avg=(key)=>Math.round(clusters.reduce((sum,cluster)=>sum+cluster[key],0)/clusters.length);
  return <div className="page mock-cluster-page">
    <header className="mock-page-heading"><div><div><h1>集群</h1><MockTag/></div><p>查看全部 EventMesh 集群的托管环境、资源使用率与消息运行状态。</p></div><Button type="primary" icon={<CopyOutlined/>} onClick={()=>setCopyId(clusters[0].id)}>复制集群</Button></header>
    <section className="mock-summary-strip"><div><span>集群总数</span><strong>{clusters.length}</strong><small>{clusters.filter((item)=>item.status==="healthy").length} 个正常 · {clusters.filter((item)=>item.status==="warning").length} 个需关注 · {clusters.filter((item)=>item.status==="unknown").length} 个未知</small></div><div><span>Runtime 节点</span><strong>{clusters.reduce((sum,item)=>sum+item.runtimes,0)}</strong><small>分布在 {clusters.length} 个集群</small></div><div><span>平均 CPU</span><strong>{avg("cpu")}%</strong><small>集群资源使用率</small></div><div><span>平均内存</span><strong>{avg("memory")}%</strong><small>集群资源使用率</small></div><div><span>消息速率</span><strong>{formatRate(clusters.reduce((sum,item)=>sum+item.inRate,0))}</strong><small>总流入速率</small></div></section><CopyTaskPanel tasks={copyTasks}/>
    <section className="panel mock-cluster-table-panel"><div className="mock-table-toolbar"><div><h2>所有集群</h2><span>点击整行进入集群详情</span></div><div><Input prefix={<SearchOutlined/>} allowClear value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索集群名称或地域"/><Select value={hosting} onChange={setHosting} options={[{value:"all",label:"全部托管方式"},{value:"Kubernetes",label:"Kubernetes"},{value:"主机集群",label:"主机集群"}]}/><Button icon={<ReloadOutlined/>}>刷新</Button></div></div>
      <div className="resource-table-wrap"><table className="resource-table mock-cluster-table"><thead><tr><th>集群</th><th>状态</th><th>托管方式</th><th>节点</th><th>资源使用率</th><th>MQ 速率</th><th>地域 / 版本</th><th>操作</th></tr></thead><tbody>{filtered.map((cluster)=>{const openCluster=()=>navigate(`/clusters/${cluster.id}/overview`);return <tr key={cluster.id} tabIndex={0} onClick={openCluster} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openCluster();}}}><td><span className="mock-cluster-identity"><i><ClusterOutlined/></i><span><strong>{cluster.name}</strong><small>{cluster.description}</small></span></span></td><td><Status value={cluster.status}/></td><td><span className="hosting-cell"><strong>{cluster.hostingType}</strong><small>{cluster.hosting}</small><small>{cluster.kubernetes}</small></span></td><td><strong>{cluster.runtimes}</strong> Runtime<br/><small>{cluster.metaNodes} Meta</small></td><td><div className="compact-usage"><UsageBar label="CPU" value={cluster.cpu}/><UsageBar label="内存" value={cluster.memory}/></div></td><td><span className="rate-cell"><strong>入 {formatRate(cluster.inRate)}</strong><small>出 {formatRate(cluster.outRate)}</small></span></td><td><span className="hosting-cell"><strong>{cluster.region}</strong><small>v{cluster.version}</small></span></td><td><span className="row-action-buttons"><Button type="link" onClick={(event)=>{event.stopPropagation();openCluster();}}>管理</Button><Button type="link" icon={<CopyOutlined/>} onClick={(event)=>{event.stopPropagation();setCopyId(cluster.id);}}>复制</Button></span></td></tr>;})}</tbody></table>{!filtered.length&&<div className="mock-empty"><SearchOutlined/><strong>未找到匹配集群</strong><span>请调整搜索或托管方式筛选。</span></div>}</div>
    </section><ClusterCopyModal open={Boolean(copyId)} sourceId={copyId} onClose={()=>setCopyId(null)} onCreate={startCopyTask} clusters={clusters}/>
  </div>;
}

function MessageRateChart(){ const option=useMemo(()=>({animationDuration:500,color:["#225aa0","#4cb6d4"],tooltip:{trigger:"axis"},legend:{right:8,top:0,itemWidth:18,textStyle:{color:"#5f7388"},data:["流入","流出"]},grid:{left:50,right:22,top:42,bottom:32},xAxis:{type:"category",boundaryGap:false,data:mockMessageSeries.labels,axisLine:{lineStyle:{color:"#b9c9d9"}},axisLabel:{color:"#6b7e92"}},yAxis:{type:"value",name:"K 条/s",splitLine:{lineStyle:{color:"#e5edf5"}},axisLabel:{color:"#6b7e92"}},series:[{name:"流入",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},data:mockMessageSeries.inbound},{name:"流出",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},data:mockMessageSeries.outbound}]}),[]); return <ReactECharts option={option} style={{height:270}}/>; }
function RuntimeResourceChart(){ const option=useMemo(()=>({animationDuration:500,color:["#225aa0","#72869b"],tooltip:{trigger:"axis",valueFormatter:(value)=>`${value}%`},legend:{right:8,top:0,itemWidth:18,textStyle:{color:"#5f7388"},data:["CPU","内存"]},grid:{left:48,right:22,top:42,bottom:32},xAxis:{type:"category",boundaryGap:false,data:mockMessageSeries.labels,axisLine:{lineStyle:{color:"#b9c9d9"}},axisLabel:{color:"#6b7e92"}},yAxis:{type:"value",min:0,max:100,axisLabel:{formatter:"{value}%",color:"#6b7e92"},splitLine:{lineStyle:{color:"#e5edf5"}}},series:[{name:"CPU",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},areaStyle:{opacity:.05},data:[39,42,41,45,48,46,49,51,47,50,46,48]},{name:"内存",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},data:[55,57,58,60,62,61,64,65,63,66,64,62]}]}),[]); return <ReactECharts option={option} style={{height:270}}/>; }
function MonitorTrendChart({series,unit}){ const option=useMemo(()=>({animationDuration:500,color:["#225aa0","#72869b","#4cb6d4"],tooltip:{trigger:"axis"},legend:{right:8,top:0,itemWidth:18,textStyle:{color:"#5f7388"},data:series.map((item)=>item.name)},grid:{left:50,right:22,top:42,bottom:32},xAxis:{type:"category",boundaryGap:false,data:mockMessageSeries.labels,axisLine:{lineStyle:{color:"#b9c9d9"}},axisLabel:{color:"#6b7e92"}},yAxis:{type:"value",name:unit,splitLine:{lineStyle:{color:"#e5edf5"}},axisLabel:{color:"#6b7e92"}},series:series.map((item,index)=>({...item,type:"line",smooth:true,symbol:"none",lineStyle:{width:2},areaStyle:index===0?{opacity:.05}:undefined}))}),[series,unit]); return <ReactECharts option={option} style={{height:270}}/>; }
function ModuleMonitoringOverview({title,description,kpis,charts,health}){
  return <div className="mock-runtime-monitoring"><section className="panel mock-monitor-summary"><div className="mock-section-title"><div><h2>{title}</h2><p>{description}</p></div><Select defaultValue="2h" options={[{value:"2h",label:"最近 2 小时"},{value:"24h",label:"最近 24 小时"}]}/></div><div className="mock-monitor-kpis">{kpis.map((item)=><span key={item.label}><small>{item.label}</small><strong>{item.value}</strong><em>{item.note}</em></span>)}</div></section><div className="mock-monitor-charts">{charts.map((chart)=><section className="panel" key={chart.title}><div className="mock-section-title"><div><h2>{chart.title}</h2><p>{chart.description}</p></div></div><MonitorTrendChart series={chart.series} unit={chart.unit}/></section>)}</div><section className="panel mock-monitor-health"><div className="mock-section-title"><div><h2>运行健康</h2><p>关键状态与需要关注的运行信号</p></div></div><div className="mock-health-cells">{health.map((item)=><span key={item.label} className={item.warning?"warning":""}>{item.warning?<ExclamationCircleOutlined/>:<CheckCircleOutlined/>}<small>{item.label}</small><strong>{item.value}</strong><em>{item.note}</em></span>)}</div></section></div>;
}
function ComponentOverview({title,description,types,relations,currentClusterId,onOpenList,onOpenRelations}){
  const inventory=mockComponentClusters.filter((item)=>types.includes(item.type));
  const currentRelations=relations.filter((item)=>item.eventMeshClusterId===currentClusterId&&types.includes(item.componentType));
  const relatedIds=new Set(currentRelations.map((item)=>item.componentClusterId));
  const related=inventory.filter((item)=>relatedIds.has(item.id));
  const nodes=related.flatMap((item)=>item.nodes);
  const healthy=nodes.filter((item)=>item.status==="healthy").length;
  const reverseReferences=relations.filter((item)=>types.includes(item.componentType)).length;
  return <div className="mock-component-overview">
    <section className="panel mock-monitor-summary"><div className="mock-section-title"><div><h2>{title}</h2><p>{description}</p></div><MockTag/></div><div className="mock-monitor-kpis four"><span><small>已关联集群</small><strong>{related.length}</strong><em>可选 {inventory.length} 套</em></span><span><small>实例 / Broker</small><strong>{nodes.length}</strong><em>{healthy} 个状态正常</em></span><span><small>健康集群</small><strong>{related.filter((item)=>item.status==="healthy").length} / {related.length}</strong><em>按组件集群汇总</em></span><span><small>反向引用</small><strong>{reverseReferences}</strong><em>多 EventMesh 共享关系</em></span></div></section>
    <section className="panel mock-related-summary"><div className="mock-section-title"><div><h2>当前 EventMesh 的关联摘要</h2><p>组件集群与 EventMesh 保持独立，可被多个 EventMesh 集群复用</p></div><div className="mock-heading-actions"><Button onClick={onOpenRelations}>管理关联</Button><Button type="primary" onClick={onOpenList}>查看集群</Button></div></div>{related.length?<div className="mock-related-lines">{related.map((item)=><button key={item.id} onClick={onOpenList}><span className={`component-type-mark ${item.type}`}>{componentTypeCopy[item.type]}</span><span><strong>{item.name}</strong><small>{item.description}</small></span><Status value={item.status}/><b>{item.nodes.length} 个实例</b></button>)}</div>:<div className="mock-empty compact"><LinkOutlined/><strong>尚未关联组件集群</strong><span>通过“管理关联”选择可复用的组件集群。</span></div>}</section>
  </div>;
}

function ComponentClusterList({title,description,types,relations,currentClusterId,onOpenRelations,onOpenTopology,onOpenCluster=null}){
  const [query,setQuery]=useState("");
  const [status,setStatus]=useState("all");
  const items=mockComponentClusters.filter((item)=>types.includes(item.type)&&`${item.name} ${item.region} ${item.description}`.toLowerCase().includes(query.toLowerCase())&&(status==="all"||item.status===status));
  const currentIds=new Set(relations.filter((item)=>item.eventMeshClusterId===currentClusterId).map((item)=>item.componentClusterId));
  return <section className="panel mock-tab-panel mock-component-list"><div className="mock-table-toolbar"><div><h2>{title}</h2><span>{description}</span></div><div><Input prefix={<SearchOutlined/>} allowClear value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索集群名称或地域"/><Select value={status} onChange={setStatus} options={[{value:"all",label:"全部状态"},{value:"healthy",label:"正常"},{value:"warning",label:"需关注"},{value:"unknown",label:"未知"}]}/><Button type="primary" icon={<LinkOutlined/>} onClick={onOpenRelations}>管理关联</Button></div></div><div className="resource-table-wrap"><table className="resource-table mock-component-table"><thead><tr><th>组件集群</th><th>类型</th><th>状态</th><th>实例 / Broker</th><th>地域 / 版本</th><th>被 EventMesh 关联</th><th>当前集群</th><th>操作</th></tr></thead><tbody>{items.map((item)=>{const references=relations.filter((relation)=>relation.componentClusterId===item.id).length;const open=()=>onOpenCluster?.(item);return <tr key={item.id} className={onOpenCluster?"clickable":""} tabIndex={onOpenCluster?0:undefined} onClick={open} onKeyDown={(event)=>{if(onOpenCluster&&(event.key==="Enter"||event.key===" ")){event.preventDefault();open();}}}><td><span className="mock-cluster-identity"><i>{item.type==="runtime"?<CloudServerOutlined/>:item.type==="meta"?<DatabaseOutlined/>:<HddOutlined/>}</i><span><strong>{item.name}</strong><small>{item.description}</small></span></span></td><td><span className={`component-type-mark ${item.type}`}>{componentTypeCopy[item.type]}</span></td><td><Status value={item.status}/></td><td><strong>{item.nodes.length}</strong><br/><small>{item.type==="runtime"?"Runtime":item.type==="meta"?"Meta 节点":"Broker"}</small></td><td><span className="hosting-cell"><strong>{item.region}</strong><small>v{item.version}</small></span></td><td><strong>{references}</strong> 个集群</td><td>{currentIds.has(item.id)?<span className="mock-status healthy"><CheckCircleOutlined/>已关联</span>:<span className="mock-status unknown"><LinkOutlined/>未关联</span>}</td><td><span className="row-action-buttons">{onOpenCluster&&<Button type="link" onClick={(event)=>{event.stopPropagation();open();}}>管理</Button>}<Button type="link" onClick={(event)=>{event.stopPropagation();onOpenTopology();}}>查看拓扑</Button></span></td></tr>;})}</tbody></table>{!items.length&&<div className="mock-empty"><SearchOutlined/><strong>未找到匹配集群</strong><span>请调整搜索词或状态筛选。</span></div>}</div></section>;
}

function RuntimeNodeList({clusters,onAdd}){
  const nodes=clusters.flatMap((item)=>item.nodes.map((node)=>({...node,clusterName:item.name})));
  return <ModuleTable title="Runtime 列表" description="当前 EventMesh 已关联 Runtime 集群中的运行实例" columns={["Runtime","所属集群","地址","CPU / 内存","消息速率","状态"]} rows={nodes.map((node)=>[<strong>{node.name}</strong>,node.clusterName,node.address,`${node.cpu??0}% / ${node.memory??0}%`,node.rate??"—",<Status value={node.status}/>])} action={<Button type="primary" icon={<PlusOutlined/>} onClick={onAdd}>添加节点</Button>}/>;
}

function RelationModal({open,onClose,currentClusterId,relations,types,onSubmit}){
  const [selected,setSelected]=useState([]);
  useEffect(()=>{if(open)setSelected([]);},[open]);
  const connected=new Set(relations.filter((item)=>item.eventMeshClusterId===currentClusterId).map((item)=>item.componentClusterId));
  const groups=types.map((type)=>({type,items:mockComponentClusters.filter((item)=>item.type===type)}));
  return <Modal className="mock-relation-modal" width={760} title="关联组件集群" open={open} onCancel={onClose} onOk={()=>{onSubmit(selected);onClose();}} okText="建立关联" cancelText="取消" okButtonProps={{disabled:!selected.length}}><div className="mock-flow-note"><LinkOutlined/><div><strong>EventMesh 依赖组件集群</strong><span>同一套 Runtime、Meta 或存储集群可以被多个 EventMesh 集群复用；已存在的关系不可重复添加。</span></div></div><div className="mock-relation-groups">{groups.map((group)=><section key={group.type}><div><strong>{componentTypeCopy[group.type]} 集群</strong><span>{group.items.filter((item)=>connected.has(item.id)).length} 个已关联</span></div><Checkbox.Group value={selected} onChange={setSelected} options={group.items.map((item)=>({value:item.id,disabled:connected.has(item.id),label:<span className="relation-option-copy"><b>{item.name}</b><small>{item.region} · {item.nodes.length} 个实例{connected.has(item.id)?" · 已关联":""}</small></span>}))}/></section>)}</div></Modal>;
}

function RelationManager({title,description,types,relations,currentClusterId,eventMeshClusters,onAdd,onRemove,onOpenTopology}){
  const {message,modal}=AntApp.useApp();
  const [query,setQuery]=useState("");
  const [open,setOpen]=useState(false);
  const candidates=relations.filter((relation)=>types.includes(relation.componentType)).map((relation)=>({relation,component:mockComponentClusters.find((item)=>item.id===relation.componentClusterId),source:eventMeshClusters.find((item)=>item.id===relation.eventMeshClusterId)})).filter((item)=>item.component&&item.source).filter((item)=>`${item.component.name} ${item.source.name} ${componentTypeCopy[item.component.type]}`.toLowerCase().includes(query.toLowerCase()));
  const attach=(ids)=>{onAdd(ids);message.success(`已建立 ${ids.length} 条模拟关联`);};
  const detach=(item)=>modal.confirm({title:"解除组件关联？",content:`${item.source.name} 将不再依赖 ${item.component.name}，拓扑会立即更新。`,okText:"解除关联",cancelText:"取消",okButtonProps:{danger:true},onOk:()=>{onRemove(item.relation.id);message.success("关联已解除");}});
  return <><section className="panel mock-tab-panel mock-relation-panel"><div className="mock-table-toolbar"><div><h2>{title}</h2><span>{description}</span></div><div><Input prefix={<SearchOutlined/>} allowClear value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索组件或 EventMesh"/><Button type="primary" icon={<LinkOutlined/>} onClick={()=>setOpen(true)}>关联集群</Button></div></div><div className="resource-table-wrap"><table className="resource-table mock-relation-table"><thead><tr><th>组件类型</th><th>组件集群</th><th>关联来源</th><th>关系状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{candidates.map((item)=><tr key={item.relation.id} className={item.relation.eventMeshClusterId===currentClusterId?"current-relation":""}><td><span className={`component-type-mark ${item.component.type}`}>{componentTypeCopy[item.component.type]}</span></td><td><span className="relation-cluster-copy"><strong>{item.component.name}</strong><small>{item.component.nodes.length} 个实例 · {item.component.region}</small></span></td><td><span className="relation-cluster-copy"><strong>{item.source.name}</strong><small>{item.relation.eventMeshClusterId===currentClusterId?"当前 EventMesh":"共享引用"}</small></span></td><td><span className="mock-status healthy"><CheckCircleOutlined/>关联生效</span></td><td>{new Date(item.relation.createdAt).toLocaleString("zh-CN",{hour12:false})}</td><td><span className="row-action-buttons"><Button type="link" onClick={()=>onOpenTopology(item.source.id)}>查看拓扑</Button>{item.relation.eventMeshClusterId===currentClusterId&&<Button type="link" danger icon={<DeleteOutlined/>} onClick={()=>detach(item)}>解除</Button>}</span></td></tr>)}</tbody></table>{!candidates.length&&<div className="mock-empty"><LinkOutlined/><strong>暂无关联记录</strong><span>点击“关联集群”选择 Runtime、Meta 或存储集群。</span></div>}</div></section><RelationModal open={open} onClose={()=>setOpen(false)} currentClusterId={currentClusterId} relations={relations} types={types} onSubmit={attach}/></>;
}

function AddNodeModal({open,onClose,onAdd}){ const {message}=AntApp.useApp(); const [role,setRole]=useState("Runtime"); const [name,setName]=useState("codex-sim-runtime-new-01"); const [spec,setSpec]=useState("4 vCPU / 8 GiB"); const submit=()=>{onAdd({id:name,name,role,address:"待分配",cpu:0,memory:0,rate:"0/s",status:"unknown"});message.success(`节点 ${name} 已加入模拟集群`);onClose();}; return <Modal title="添加集群节点" open={open} onCancel={onClose} onOk={submit} okText="添加节点" cancelText="取消" okButtonProps={{disabled:!name.trim()}}><div className="mock-flow-note"><PlusOutlined/><div><strong>添加到当前关联组件</strong><span>这是前端模拟节点，名称必须保留 codex-sim- 前缀。</span></div></div><div className="add-node-form"><label>节点角色<Select value={role} onChange={(value)=>{setRole(value);setName(value==="Runtime"?"codex-sim-runtime-new-01":"codex-sim-meta-new-01");}} options={[{value:"Runtime",label:"Runtime 节点"},{value:"Meta",label:"Meta 节点"}]}/></label><label>节点名称<Input value={name} onChange={(event)=>setName(event.target.value.startsWith("codex-sim-")?event.target.value:`codex-sim-${event.target.value}`)}/></label><label>资源规格<Select value={spec} onChange={setSpec} options={["2 vCPU / 4 GiB","4 vCPU / 8 GiB","8 vCPU / 16 GiB"].map((value)=>({value,label:value}))}/></label></div></Modal>; }

function ModuleTable({title,description,columns,rows,action=null}){
  const normalizedRows=rows.map((cells,index)=>({key:`${title}-${index}`,cells}));
  return <ResourceTable title={title} description={description} columns={columns} rows={normalizedRows} action={action} searchable={false} showRefresh={false} sectionClassName="panel mock-tab-panel mock-module-panel" tableClassName="resource-table mock-module-table"/>;
}

function buildMockTopology(cluster,relations){
  const clusterTypes={runtime:"EVENTMESH_RUNTIME_CLUSTER",meta:"META_CLUSTER",kafka:"STORAGE_KAFKA_CLUSTER",rocketmq:"STORAGE_ROCKETMQ_CLUSTER"};
  const children=relations.filter((item)=>item.eventMeshClusterId===cluster.id).flatMap((item)=>{const component=mockComponentClusters.find((candidate)=>candidate.id===item.componentClusterId);if(!component)return[];return [{key:`cluster-${component.id}`,id:component.id,kind:"cluster",relation:"CLUSTER_RELATIONSHIP",name:component.name,status:component.status,clusterType:clusterTypes[component.type],version:component.version,description:component.description,children:component.nodes.map((node)=>({key:`node-${node.id}`,id:node.id,kind:"runtime",relation:"RUNTIME_MEMBER",name:node.name,status:node.status,host:String(node.address).split(":")[0],port:String(node.address).split(":")[1],version:component.version}))}];});
  return {root:{key:`cluster-${cluster.id}`,id:cluster.id,kind:"cluster",relation:"ROOT",name:cluster.name,status:"Healthy",clusterType:"EVENTMESH_CLUSTER",version:cluster.version,description:cluster.description,children},runtimes:[]};
}

function ClusterLandscapeOverview({cluster,relatedComponents,navigate}){
  const rows=[
    {id:cluster.id,name:cluster.name,description:cluster.description,type:"eventmesh",status:cluster.status,region:cluster.region,version:cluster.version,resourceCount:1,resourceLabel:"EventMesh 集群",relation:"当前管理对象"},
    ...relatedComponents.map((item)=>({...item,resourceCount:item.nodes.length,resourceLabel:item.type==="runtime"?"Runtime 实例":item.type==="meta"?"Meta 节点":"Broker",relation:"依赖组件"})),
  ];
  const healthyCount=rows.filter((item)=>item.status==="healthy").length;
  const warningCount=rows.filter((item)=>item.status==="warning").length;
  const runtimeClusters=relatedComponents.filter((item)=>item.type==="runtime");
  const metaClusters=relatedComponents.filter((item)=>item.type==="meta");
  const storageClusters=relatedComponents.filter((item)=>item.type==="kafka"||item.type==="rocketmq");
  const openRow=(item)=>{
    if(item.type==="eventmesh")navigate(`/clusters/${cluster.id}/overview`);
    else if(item.type==="runtime")navigate(`/clusters/${cluster.id}/runtime?section=clusters`);
    else if(item.type==="meta")navigate(`/clusters/${cluster.id}/meta?section=clusters`);
    else navigate(storageClusterConsolePath(cluster.id,item.type,item.id));
  };
  const iconFor=(type)=>type==="eventmesh"?<ClusterOutlined/>:type==="runtime"?<CloudServerOutlined/>:type==="meta"?<DatabaseOutlined/>:<HddOutlined/>;
  const labelFor=(type)=>type==="eventmesh"?"EventMesh":componentTypeCopy[type];
  return <div className="mock-landscape-overview">
    <header className="mock-page-heading"><div><div><h1>概览</h1><MockTag/></div><p>查看当前 EventMesh 以及关联的 Runtime、Meta、Kafka 和 RocketMQ 集群整体信息。</p></div><div className="mock-heading-actions"><Button icon={<ApartmentOutlined/>} onClick={()=>navigate(`/clusters/${cluster.id}/topology`)}>查看拓扑</Button><Button type="primary" icon={<LinkOutlined/>} onClick={()=>navigate(`/clusters/${cluster.id}/relations`)}>管理关联</Button></div></header>
    <section className="mock-summary-strip mock-landscape-summary"><div><span>集群总数</span><strong>{rows.length}</strong><small>1 个 EventMesh · {relatedComponents.length} 个组件集群</small></div><div><span>整体状态</span><strong>{healthyCount} / {rows.length}</strong><small>{warningCount?`${warningCount} 个集群需关注`:"全部集群运行正常"}</small></div><div><span>Runtime 实例</span><strong>{runtimeClusters.flatMap((item)=>item.nodes).length}</strong><small>分布在 {runtimeClusters.length} 套 Runtime 集群</small></div><div><span>Meta 节点</span><strong>{metaClusters.flatMap((item)=>item.nodes).length}</strong><small>分布在 {metaClusters.length} 套 Meta 集群</small></div><div><span>存储 Broker</span><strong>{storageClusters.flatMap((item)=>item.nodes).length}</strong><small>Kafka 与 RocketMQ 合计</small></div></section>
    <section className="panel mock-cluster-table-panel mock-landscape-table"><div className="mock-table-toolbar"><div><h2>集群组成</h2><span>点击整行进入对应集群模块</span></div><span className="mock-landscape-current"><DashboardOutlined/> 当前 EventMesh：{cluster.name}</span></div><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>集群</th><th>类型</th><th>在当前体系中的角色</th><th>节点 / Broker</th><th>状态</th><th>地域 / 版本</th><th>操作</th></tr></thead><tbody>{rows.map((item)=><tr key={`${item.type}-${item.id}`} tabIndex={0} onClick={()=>openRow(item)} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openRow(item);}}}><td><span className="mock-cluster-identity"><i>{iconFor(item.type)}</i><span><strong>{item.name}</strong><small>{item.description}</small></span></span></td><td><span className={`component-type-mark ${item.type}`}>{labelFor(item.type)}</span></td><td><span className="mock-landscape-role"><strong>{item.relation}</strong><small>{item.type==="eventmesh"?"承载业务主题与事件流":"由当前 EventMesh 关联使用"}</small></span></td><td><strong>{item.resourceCount}</strong><br/><small>{item.resourceLabel}</small></td><td><Status value={item.status}/></td><td><span className="hosting-cell"><strong>{item.region}</strong><small>v{item.version}</small></span></td><td><Button type="link" onClick={(event)=>{event.stopPropagation();openRow(item);}}>查看</Button></td></tr>)}</tbody></table></div></section>
  </div>;
}

export function MockClusterDetail(){
  const navigate=useNavigate();
  const location=useLocation();
  const {clusterId,view}=useParams();
  const {tasks:copyTasks,clusters,createCopyTask}=useCopyTasks();
  const {relations,addRelations,removeRelation,inheritRelations}=useMockRelations();
  const {state:writableState,addTopic,addConsumer}=useMockWritableResources();
  const cluster=clusters.find((item)=>item.id===clusterId)??clusters[0];
  const allowedViews=["summary","overview","relations","runtime","meta","storage","topics","connections","consumers","operations","messages","security","topology"];
  const activeView=allowedViews.includes(view)?view:"overview";
  const showClusterHeader=activeView==="overview"||activeView==="topology";
  const rawSection=new URLSearchParams(location.search).get("section")||"overview";
  const detailSection=rawSection==="runtime"?"runtimes":rawSection;
  useEffect(()=>{
    if(view&&!allowedViews.includes(view)){navigate(`/clusters/${cluster.id}/overview`,{replace:true});return;}
    if(view==="runtime"&&rawSection==="meta"){navigate(`/clusters/${cluster.id}/meta?section=clusters`,{replace:true});return;}
    if(view==="runtime"&&rawSection==="runtime")navigate(`/clusters/${cluster.id}/runtime?section=runtimes`,{replace:true});
  },[view,rawSection,cluster.id,navigate]);
  const [copyOpen,setCopyOpen]=useState(false);
  const [addOpen,setAddOpen]=useState(false);
  const [topicOpen,setTopicOpen]=useState(false);
  const [consumerOpen,setConsumerOpen]=useState(false);
  const [extraNodes,setExtraNodes]=useState([]);
  const startCopyTask=(payload)=>{const task=createCopyTask(payload);inheritRelations(payload.source.id,task.targetId);navigate(`/clusters/${cluster.id}/overview`);};
  const addNode=(node)=>setExtraNodes((current)=>[...current,node]);
  const currentRelations=relations.filter((item)=>item.eventMeshClusterId===cluster.id);
  const currentComponentIds=new Set(currentRelations.map((item)=>item.componentClusterId));
  const relatedComponents=mockComponentClusters.filter((item)=>currentComponentIds.has(item.id)).map((item)=>({...item,nodes:[...item.nodes,...writableState.nodes.filter((node)=>node.clusterId===item.id)]}));
  const runtimeClusters=relatedComponents.filter((item)=>item.type==="runtime").map((item,index)=>index===0?{...item,nodes:[...item.nodes,...extraNodes.filter((node)=>node.role==="Runtime")]}:item);
  const metaClusters=relatedComponents.filter((item)=>item.type==="meta").map((item,index)=>index===0?{...item,nodes:[...item.nodes,...extraNodes.filter((node)=>node.role==="Meta")]}:item);
  const storageClusters=relatedComponents.filter((item)=>item.type==="kafka"||item.type==="rocketmq");
  const topicAdditions=writableState.topics.filter((item)=>item.eventMeshClusterId===cluster.id);
  const topicRecords=[...cluster.topics.map((name,index)=>({id:`seed-topic-${index}`,name,storageClusterId:storageClusters[0]?.id,engine:storageClusters[0]?.type??"kafka",partitions:index%2?8:12,replicas:3,status:"healthy"})),...topicAdditions];
  const consumerAdditions=writableState.consumers.filter((item)=>item.eventMeshClusterId===cluster.id);
  const consumerRecords=[...cluster.consumers.map((name,index)=>({id:`seed-consumer-${index}`,name,topic:topicRecords[index%topicRecords.length]?.name??"—",members:index+2,rate:`${(18.2-index*2.1).toFixed(1)}K/s`,lag:index===1?"8.4K":"1.2K",status:index===1?"warning":"healthy"})),...consumerAdditions];
  const runtimeNodes=runtimeClusters.flatMap((item)=>item.nodes);
  const metaNodes=metaClusters.flatMap((item)=>item.nodes);
  const topologyData=useMemo(()=>buildMockTopology(cluster,relations),[cluster,relations]);
  const topologyTopics=topicRecords.map((item,index)=>({id:index+1,topicName:item.name,topicType:"NORMAL",readQueueNum:item.partitions,writeQueueNum:item.partitions,status:"Healthy"}));
  const topologyGroups=consumerRecords.map((item,index)=>({id:index+1,name:item.name,type:0,state:"ONLINE",status:"Healthy"}));
  const openTopology=(eventMeshId=cluster.id)=>navigate(`/clusters/${eventMeshId}/topology`);
  const relationManager=(types,title,description,showAllSources=true)=><RelationManager title={title} description={description} types={types} relations={showAllSources?relations:currentRelations} currentClusterId={cluster.id} eventMeshClusters={clusters} onAdd={(ids)=>addRelations(cluster.id,ids)} onRemove={removeRelation} onOpenTopology={openTopology}/>;
  const overview=<div className="mock-overview-grid">
    <section className="panel mock-hosting-panel"><div className="mock-section-title"><div><h2>托管与资源</h2><p>EventMesh 与独立组件集群的运行基础</p></div><CloudServerOutlined/></div><dl><div><dt>托管方式</dt><dd>{cluster.hosting}</dd></div><div><dt>基础设施</dt><dd>{cluster.hostingType}</dd></div><div><dt>K8s 集群</dt><dd>{cluster.kubernetes}</dd></div><div><dt>关联规模</dt><dd>{relatedComponents.length} 个组件集群</dd></div></dl><div className="mock-usage-stack"><UsageBar label="CPU" value={cluster.cpu}/><UsageBar label="内存" value={cluster.memory}/><UsageBar label="存储" value={cluster.storage}/></div></section>
    <section className="panel mock-runtime-summary"><div className="mock-section-title"><div><h2>Runtime 集群</h2><p>消息接入与路由，与 Broker 分离</p></div><ApartmentOutlined/></div><strong>{runtimeClusters.length}</strong><span>套关联集群</span><div><small>Runtime 实例</small><b>{runtimeNodes.length}</b></div><div><small>反向引用</small><b>{relations.filter((item)=>item.componentType==="runtime"&&currentComponentIds.has(item.componentClusterId)).length}</b></div><Button type="link" onClick={()=>navigate(`/clusters/${cluster.id}/runtime?section=clusters`)}>查看 Runtime 集群</Button></section>
    <section className="panel mock-runtime-summary"><div className="mock-section-title"><div><h2>Meta 集群</h2><p>注册、发现与元数据协调</p></div><DatabaseOutlined/></div><strong>{metaClusters.length}</strong><span>套关联集群</span><div><small>Meta 节点</small><b>{metaNodes.length}</b></div><div><small>Leader</small><b>{metaClusters.length}</b></div><Button type="link" onClick={()=>navigate(`/clusters/${cluster.id}/meta?section=clusters`)}>查看 Meta 集群</Button></section>
    <section className="panel mock-storage-summary"><div className="mock-section-title"><div><h2>存储集群</h2><p>Kafka 与 RocketMQ Broker 独立托管</p></div><HddOutlined/></div><div className="mock-storage-lines"><button onClick={()=>navigate(`/clusters/${cluster.id}/storage?section=kafka`)}><span>Kafka 集群</span><strong>{storageClusters.filter((item)=>item.type==="kafka").length}</strong><small>{storageClusters.filter((item)=>item.type==="kafka").flatMap((item)=>item.nodes).length} Brokers</small></button><button onClick={()=>navigate(`/clusters/${cluster.id}/storage?section=rocketmq`)}><span>RocketMQ 集群</span><strong>{storageClusters.filter((item)=>item.type==="rocketmq").length}</strong><small>{storageClusters.filter((item)=>item.type==="rocketmq").flatMap((item)=>item.nodes).length} Brokers</small></button></div><Button type="link" onClick={()=>navigate(`/clusters/${cluster.id}/relations`)}>管理全部关联</Button></section>
    <section className="panel mock-chart-panel"><div className="mock-section-title"><div><h2>MQ 消费情况与速率</h2><p>最近 2 小时消息流入与消费速率</p></div><Select defaultValue="2h" options={[{value:"2h",label:"最近 2 小时"},{value:"24h",label:"最近 24 小时"}]}/></div><div className="mock-rate-kpis"><span><small>流入速率</small><strong>{formatRate(cluster.inRate)}</strong></span><span><small>消费速率</small><strong>{formatRate(cluster.outRate)}</strong></span><span><small>消费积压</small><strong>12.6K</strong></span><span><small>平均延迟</small><strong>38 ms</strong></span></div><MessageRateChart/></section>
    <section className="panel mock-resource-table"><div className="mock-section-title"><div><h2>消息资源</h2><p>Topic 与消费者运行概览</p></div><TeamOutlined/></div><table><thead><tr><th>资源类型</th><th>数量</th><th>活跃</th><th>消息速率</th><th>积压</th></tr></thead><tbody><tr><td>Topic</td><td>{cluster.topics.length}</td><td>{cluster.topics.length}</td><td>{formatRate(cluster.inRate)}</td><td>—</td></tr><tr><td>消费者</td><td>{cluster.consumers.length}</td><td>{cluster.consumers.length}</td><td>{formatRate(cluster.outRate)}</td><td>12.6K</td></tr></tbody></table></section>
  </div>;
  const openComponentConsole=(item)=>navigate(componentClusterConsolePath(cluster.id,item.type,item.id));
  const runtimeView=detailSection==="clusters"?<ComponentClusterList title="Runtime 集群列表" description="选择集群进入 Runtime 控制面板" types={["runtime"]} relations={relations} currentClusterId={cluster.id} onOpenRelations={()=>navigate(`/clusters/${cluster.id}/runtime?section=relations`)} onOpenTopology={openTopology} onOpenCluster={openComponentConsole}/>:detailSection==="runtimes"?<RuntimeNodeList clusters={runtimeClusters} onAdd={()=>setAddOpen(true)}/>:detailSection==="relations"?relationManager(["runtime"],"Runtime 被关联列表","查看 Runtime 集群被哪些 EventMesh 集群复用"):<ComponentOverview title="Runtime 集群概要" description="汇总当前 EventMesh 的 Runtime 集群、运行实例与反向引用" types={["runtime"]} relations={relations} currentClusterId={cluster.id} onOpenList={()=>navigate(`/clusters/${cluster.id}/runtime?section=clusters`)} onOpenRelations={()=>navigate(`/clusters/${cluster.id}/runtime?section=relations`)}/>;
  const metaView=detailSection==="clusters"?<ComponentClusterList title="Meta 集群列表" description="选择集群进入 Meta 控制面板" types={["meta"]} relations={relations} currentClusterId={cluster.id} onOpenRelations={()=>navigate(`/clusters/${cluster.id}/meta?section=relations`)} onOpenTopology={openTopology} onOpenCluster={openComponentConsole}/>:detailSection==="relations"?relationManager(["meta"],"Meta 被关联列表","查看 Meta 集群被哪些 EventMesh 集群复用"):<ComponentOverview title="Meta 集群概要" description="汇总当前 EventMesh 的 Meta 集群、仲裁节点与反向引用" types={["meta"]} relations={relations} currentClusterId={cluster.id} onOpenList={()=>navigate(`/clusters/${cluster.id}/meta?section=clusters`)} onOpenRelations={()=>navigate(`/clusters/${cluster.id}/meta?section=relations`)}/>;
  const openStorageConsole=(item)=>navigate(storageClusterConsolePath(cluster.id,item.type,item.id));
  const storageView=detailSection==="kafka"?<ComponentClusterList title="Kafka 集群" description="选择集群进入 Kafka 控制面板" types={["kafka"]} relations={relations} currentClusterId={cluster.id} onOpenRelations={()=>navigate(`/clusters/${cluster.id}/storage?section=relations`)} onOpenTopology={openTopology} onOpenCluster={openStorageConsole}/>:detailSection==="rocketmq"?<ComponentClusterList title="RocketMQ 集群" description="选择集群进入 RocketMQ 控制面板" types={["rocketmq"]} relations={relations} currentClusterId={cluster.id} onOpenRelations={()=>navigate(`/clusters/${cluster.id}/storage?section=relations`)} onOpenTopology={openTopology} onOpenCluster={openStorageConsole}/>:detailSection==="relations"?relationManager(["kafka","rocketmq"],"存储集群被关联列表","查看 Kafka 与 RocketMQ 集群的 EventMesh 反向引用"):<ComponentOverview title="存储集群概要" description="分别汇总 Kafka 与 RocketMQ 集群及其 Broker" types={["kafka","rocketmq"]} relations={relations} currentClusterId={cluster.id} onOpenList={()=>navigate(`/clusters/${cluster.id}/storage?section=kafka`)} onOpenRelations={()=>navigate(`/clusters/${cluster.id}/storage?section=relations`)}/>;
  const topicAction=<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setTopicOpen(true)}>添加 Topic</Button>;
  const topicRows=topicRecords.map((item,index)=>{const storage=storageClusters.find((candidate)=>candidate.id===item.storageClusterId);return [<strong>{item.name}</strong>,storage?`${storage.type==="kafka"?"Kafka":"RocketMQ"} · ${storage.name}`:"未指定",item.partitions,item.replicas,index<cluster.topics.length?`${(12.8-index*1.4).toFixed(1)}K/s`:"0/s",<span className="mock-status healthy"><CheckCircleOutlined/>正常</span>];});
  const topicView=detailSection==="list"?<ModuleTable title="Topic 列表" description="当前集群的业务 Topic 与物理存储位置" columns={["Topic 名称","存储集群","分区 / 队列","副本","流入速率","状态"]} rows={topicRows} action={topicAction}/>:<div className="mock-stacked-modules"><div className="panel mock-module-actionbar"><div><strong>Topic 管理</strong><span>创建业务 Topic，并同步写入所选 Kafka 或 RocketMQ 集群</span></div>{topicAction}</div><ModuleMonitoringOverview title="Topic 监控概览" description="主题可用性、分区负载与消息吞吐" kpis={[{label:"Topic 总数",value:topicRecords.length,note:"全部可用"},{label:"分区总数",value:topicRecords.reduce((sum,item)=>sum+Number(item.partitions||0),0),note:"无离线分区"},{label:"流入速率",value:formatRate(cluster.inRate),note:"较前一小时 +4.8%"},{label:"流出速率",value:formatRate(cluster.outRate),note:"消费保持稳定"},{label:"消息存储",value:"1.84 TB",note:"使用率 38%"}]} charts={[{title:"Topic 吞吐趋势",description:"全部 Topic 流入与流出速率",unit:"K 条/s",series:[{name:"流入",data:mockMessageSeries.inbound},{name:"流出",data:mockMessageSeries.outbound}]},{title:"分区负载趋势",description:"分区写入与读取负载",unit:"%",series:[{name:"写入负载",data:[38,42,45,43,48,51,49,54,52,57,55,58]},{name:"读取负载",data:[31,34,36,38,40,39,43,45,44,48,47,49]}]}]} health={[{label:"可用 Topic",value:`${topicRecords.length} / ${topicRecords.length}`,note:"全部正常"},{label:"离线分区",value:"0",note:"无异常"},{label:"副本不足",value:"0",note:"副本同步正常"},{label:"热点 Topic",value:"1",note:"order-created 接近阈值",warning:true}]}/></div>;
  const consumerView=<ModuleTable title="Consumer" description="消费者组、积压与消费速率" columns={["消费者组","订阅 Topic","实例","消费速率","积压","状态"]} rows={consumerRecords.map((item)=>[<strong>{item.name}</strong>,item.topic,item.members,item.rate,item.lag,<span className={`mock-status ${item.status}`}>{item.status==="warning"?<ExclamationCircleOutlined/>:<CheckCircleOutlined/>}{item.status==="warning"?"需关注":"正常"}</span>])} action={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setConsumerOpen(true)}>添加 Consumer Group</Button>}/>;
  const views={
    summary:<ClusterLandscapeOverview cluster={cluster} relatedComponents={relatedComponents} navigate={navigate}/>,
    overview,
    relations:relationManager(["runtime","meta","kafka","rocketmq"],"EventMesh 关联集群","当前 EventMesh 依赖的 Runtime、Meta、Kafka 与 RocketMQ 集群",false),
    runtime:runtimeView,
    meta:metaView,
    storage:storageView,
    topics:<>{topicView}<CreateTopicModal open={topicOpen} onClose={()=>setTopicOpen(false)} eventMeshClusterId={cluster.id} storageClusters={storageClusters} existingNames={topicRecords.map((item)=>item.name)} onCreate={addTopic}/></>,
    connections:detailSection==="list"?<ModuleTable title="连接列表" description="客户端到 Runtime 的活跃连接" columns={["客户端","协议","Runtime","连接数","最近活动","状态"]} rows={[["order-gateway","HTTP","codex-sim-runtime-east-01",238,"刚刚"],["payment-adapter","TCP","codex-sim-runtime-east-02",164,"3 秒前"],["inventory-connector","MQTT","codex-sim-runtime-east-03",92,"7 秒前"]].map((row)=>[...row,<span className="mock-status healthy"><CheckCircleOutlined/>在线</span>])}/>:<ModuleMonitoringOverview title="连接监控概览" description="客户端连接规模、稳定性与协议运行状态" kpis={[{label:"活跃连接",value:"12.4K",note:`分布在 ${runtimeNodes.length} 个 Runtime`},{label:"每秒新建",value:"186/s",note:"较前一小时 +2.1%"},{label:"每秒断开",value:"14/s",note:"处于正常区间"},{label:"连接失败率",value:"0.04%",note:"目标 < 0.1%"},{label:"活跃协议",value:"3",note:"HTTP · TCP · MQTT"}]} charts={[{title:"连接数量趋势",description:"活跃连接与新建连接",unit:"连接数",series:[{name:"活跃连接",data:[10.8,11.1,11.3,11.5,11.8,11.7,12.0,12.2,12.1,12.3,12.2,12.4]},{name:"新建连接",data:[142,151,148,160,172,168,178,181,176,184,179,186]}]},{title:"连接稳定性",description:"断开与失败连接变化",unit:"次/s",series:[{name:"断开",data:[11,12,10,14,13,12,15,14,13,15,14,14]},{name:"失败",data:[2,1,2,2,3,2,2,3,2,2,1,2]}]}]} health={[{label:"在线 Runtime",value:`${runtimeNodes.filter((node)=>node.status==="healthy").length} / ${runtimeNodes.length}`,note:"可接受客户端连接"},{label:"连接成功率",value:"99.96%",note:"近 2 小时"},{label:"空闲连接占比",value:"8.2%",note:"处于正常范围"},{label:"异常客户端",value:"0",note:"未发现持续重连"}]}/>,
    consumers:<>{consumerView}<CreateConsumerModal open={consumerOpen} onClose={()=>setConsumerOpen(false)} eventMeshClusterId={cluster.id} topics={topicRecords.map((item)=>item.name)} existingNames={consumerRecords.map((item)=>item.name)} onCreate={addConsumer}/></>,
    operations:<ModuleTable title="操作历史" description="集群运维操作与复制任务执行记录" columns={["时间","操作","资源","操作者","结果"]} rows={[...copyTasks.map((task)=>[new Date(task.createdAt).toLocaleTimeString("zh-CN",{hour12:false}),"复制集群",`${task.sourceName} → ${task.targetName}`,"admin",<span className={`mock-status ${task.progress>=100?"healthy":"warning"}`}>{task.progress>=100?<CheckCircleOutlined/>:<ReloadOutlined spin/>}{task.progress>=100?"成功":`${copyTaskPhase(task.progress)} ${task.progress}%`}</span>]),...[["10:42:18","更新配置",cluster.name,"admin"],["09:17:52","创建 Topic","order-created","ops-user"],["08:55:11","关联 Runtime 集群","codex-sim-runtime-east-primary","admin"]].map((row)=>[...row,<span className="mock-status healthy"><CheckCircleOutlined/>成功</span>]) ]}/>,
    messages:<section className="panel mock-tab-panel"><div className="mock-section-title"><div><h2>Message</h2><p>MQ 流入、消费速率与积压趋势</p></div><HddOutlined/></div><div className="mock-rate-kpis wide"><span><small>Topic</small><strong>{cluster.topics.length}</strong></span><span><small>消费者</small><strong>{cluster.consumers.length}</strong></span><span><small>流入速率</small><strong>{formatRate(cluster.inRate)}</strong></span><span><small>消费速率</small><strong>{formatRate(cluster.outRate)}</strong></span></div><MessageRateChart/></section>,
    security:<ModuleTable title="Security" description="集群安全策略与访问控制（模拟配置）" columns={["策略","范围","状态","最近更新"]} rows={[["TLS 传输加密","全部 Runtime","已启用","2026-08-18 09:30"],["Topic ACL","生产 Topic","已启用","2026-08-17 16:12"],["管理网络白名单","10.18.0.0/16","已启用","2026-08-16 11:05"]].map((row)=>[row[0],row[1],<span className="mock-status healthy"><CheckCircleOutlined/>{row[2]}</span>,row[3]])}/>,
    topology:<div className="mock-topology-view"><TopologyExperience cluster={{...cluster,clusterId:cluster.id,clusterType:"EVENTMESH_CLUSTER",status:"Healthy"}} topology={topologyData.root} runtimes={topologyData.runtimes} topics={topologyTopics} groups={topologyGroups} error={null} loading={false} fetching={false} fetchedAt={new Date().toISOString()} onRefresh={()=>{}} onExit={()=>navigate(`/clusters/${cluster.id}/overview`)}/></div>,
  };
  return <div className="page mock-cluster-detail">{showClusterHeader&&<><section className="mock-detail-hero"><div><button onClick={()=>navigate("/clusters")}>全部集群 /</button><div className="mock-detail-title"><h1>{cluster.name}</h1><Status value={cluster.status}/><MockTag/></div><p>{cluster.description}</p><div className="mock-detail-meta"><span>版本 {cluster.version}</span><span>{cluster.region}</span><span>运行 {cluster.uptime}</span><span>集群 ID {cluster.id}</span></div></div><div className="mock-detail-actions"><Button icon={<CopyOutlined/>} onClick={()=>setCopyOpen(true)}>复制集群</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setAddOpen(true)}>添加节点</Button></div></section>{activeView==="overview"&&<CopyTaskPanel tasks={copyTasks}/>}<div className="mock-cluster-view-heading"><strong>{activeView==="overview"?"EventMesh 集群概要":"集群拓扑"}</strong><span>当前集群 · {cluster.name}</span></div></>}{views[activeView]}<ClusterCopyModal open={copyOpen} sourceId={cluster.id} onClose={()=>setCopyOpen(false)} onCreate={startCopyTask} clusters={clusters}/><AddNodeModal open={addOpen} onClose={()=>setAddOpen(false)} onAdd={addNode}/></div>;
}
