import { useEffect, useMemo, useState } from "react";
import { CheckCircleOutlined, CloudServerOutlined, ClusterOutlined, CopyOutlined, DatabaseOutlined, ExclamationCircleOutlined, HddOutlined, PlusOutlined, ReloadOutlined, SearchOutlined, SettingOutlined, TeamOutlined } from "@ant-design/icons";
import { App as AntApp, Button, Checkbox, Input, Modal, Select, Tabs, Tag } from "antd";
import ReactECharts from "echarts-for-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { mockClusters, mockMessageSeries, mockMetaNodes, mockRuntimeNodes } from "./mockClusterData";
import { TopologyExperience } from "./TopologyExperience";

const statusMap = { healthy:{ label:"正常", icon:<CheckCircleOutlined/> }, warning:{ label:"需关注", icon:<ExclamationCircleOutlined/> }, unknown:{ label:"状态未知", icon:<SettingOutlined/> } };
const MockTag = () => <Tag className="mock-source-tag">MOCK DATA</Tag>;
function Status({ value }) { const item=statusMap[value]??statusMap.unknown; return <span className={`mock-status ${value}`}>{item.icon}{item.label}</span>; }
function UsageBar({ label, value }) { const tone=value>=80?"critical":value>=70?"warning":"normal"; return <div className="usage-row"><span>{label}</span><div><i className={tone} style={{width:`${value}%`}}/></div><strong>{value}%</strong></div>; }
const formatRate=(value)=>value>=1000?`${(value/1000).toFixed(1)}K/s`:`${value}/s`;

const copyStateKey="eventmesh-mock-copy-state-v2";
const emptyCopyState={tasks:[],copiedClusters:[]};
function readCopyState(){ if(typeof window==="undefined")return emptyCopyState; try{ const saved=JSON.parse(window.localStorage.getItem(copyStateKey)||"null"); return saved&&Array.isArray(saved.tasks)&&Array.isArray(saved.copiedClusters)?saved:emptyCopyState; }catch{return emptyCopyState;} }
function writeCopyState(state){ if(typeof window!=="undefined")window.localStorage.setItem(copyStateKey,JSON.stringify(state)); }
function copiedClusterFromTask(task){ return {...task.sourceSnapshot,id:task.targetId,name:task.targetName,description:`从 ${task.sourceName} 复制创建的集群`,status:"healthy",uptime:"刚刚创建",cpu:0,memory:0,storage:0,inRate:0,outRate:0,topics:task.topics,consumers:task.consumers}; }

function useCopyTasks() {
  const [copyState,setCopyState]=useState(readCopyState);
  useEffect(()=>{ const timer=window.setInterval(()=>setCopyState((current)=>{ let changed=false; const tasks=current.tasks.map((task)=>{ if(task.progress>=100)return task; changed=true; return {...task,progress:Math.min(100,task.progress+8)}; }); const copiedClusters=[...current.copiedClusters]; tasks.forEach((task)=>{ if(task.progress>=100&&!copiedClusters.some((cluster)=>cluster.id===task.targetId)){copiedClusters.unshift(copiedClusterFromTask(task));changed=true;} }); if(!changed)return current; const next={tasks,copiedClusters}; writeCopyState(next); return next; }),1200); return()=>window.clearInterval(timer); },[]);
  const createCopyTask=({source,targetName,topics,consumers})=>setCopyState((current)=>{ const stamp=Date.now(); const safeName=targetName.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"")||"eventmesh-copy"; const existingIds=new Set([...mockClusters,...current.copiedClusters].map((cluster)=>cluster.id)); const targetId=existingIds.has(safeName)?`${safeName}-${String(stamp).slice(-5)}`:safeName; const task={id:`copy-${stamp}`,targetId,createdAt:new Date().toISOString(),progress:8,sourceName:source.name,targetName:targetName.trim(),topicCount:topics.length,consumerCount:consumers.length,runtimes:source.runtimes,metaNodes:source.metaNodes,topics:[...topics],consumers:[...consumers],sourceSnapshot:{...source}}; const next={...current,tasks:[task,...current.tasks]}; writeCopyState(next); return next; });
  return {tasks:copyState.tasks,copiedClusters:copyState.copiedClusters,clusters:[...mockClusters,...copyState.copiedClusters],createCopyTask};
}

function copyTaskPhase(progress){ if(progress>=100)return "复制完成"; if(progress>=82)return "初始化目标集群"; if(progress>=52)return "复制 Topic 与消费者"; if(progress>=24)return "复制 Runtime 与 Meta"; return "校验集群配置"; }

function CopyTaskPanel({tasks}) {
  const activeTasks=tasks.filter((task)=>task.progress<100);
  if(!activeTasks.length)return null;
  return <section className="panel mock-copy-task-panel"><div className="mock-copy-task-heading"><div><h2>集群复制任务</h2><p>完成后自动收起，可在操作历史中查看结果</p></div><span>{activeTasks.length} 个进行中</span></div><div className="mock-copy-task-list">{activeTasks.map((task)=><article key={task.id}><div className="mock-copy-task-icon running"><ReloadOutlined spin/></div><div className="mock-copy-task-main"><div><strong>{task.targetName}</strong><span>{task.sourceName} → {task.targetName}</span></div><div className="mock-copy-task-meta"><span>{copyTaskPhase(task.progress)}</span><span>{task.topicCount} Topics</span><span>{task.consumerCount} 消费者</span><span>{task.runtimes} Runtime · {task.metaNodes} Meta</span></div><div className="mock-copy-progress"><i style={{width:`${task.progress}%`}}/></div></div><div className="mock-copy-task-state"><strong>{task.progress}%</strong><span>进行中</span></div></article>)}</div></section>;
}

function ClusterCopyModal({ open, sourceId, onClose, onCreate, clusters=mockClusters }) {
  const { message }=AntApp.useApp();
  const initial=clusters.find((cluster)=>cluster.id===sourceId)??clusters[0];
  const [selectedId,setSelectedId]=useState(initial.id); const selected=clusters.find((cluster)=>cluster.id===selectedId)??initial;
  const [name,setName]=useState(`${initial.name}-copy`); const [topics,setTopics]=useState(initial.topics); const [consumers,setConsumers]=useState(initial.consumers);
  const reset=(id)=>{ const next=clusters.find((cluster)=>cluster.id===id)??initial; setSelectedId(id); setName(`${next.name}-copy`); setTopics(next.topics); setConsumers(next.consumers); };
  useEffect(()=>{ if(open&&sourceId) reset(sourceId); },[open,sourceId]);
  const submit=()=>{ onCreate?.({source:selected,targetName:name,topics,consumers}); message.success(`已创建复制任务：${name}`); onClose(); };
  return <Modal className="cluster-copy-modal" width={760} title="复制整个集群" open={open} onCancel={onClose} onOk={submit} okText="开始复制" cancelText="取消" okButtonProps={{disabled:!name.trim()}}>
    <div className="mock-flow-note"><CopyOutlined/><div><strong>以集群为单位复制</strong><span>复制 Runtime 与 Meta 集群结构，并可选择随集群复制的 Topic 和消费者。这里不会生成单独的 Topic 或消费者副本。</span></div></div>
    <div className="copy-form-grid"><label>源集群<Select value={selected.id} onChange={reset} options={clusters.map((cluster)=>({value:cluster.id,label:cluster.name}))}/></label><label>新集群名称<Input value={name} onChange={(event)=>setName(event.target.value)}/></label></div>
    <div className="copy-resource-columns"><section><div><strong>选择 Topic</strong><span>{topics.length} / {selected.topics.length}</span></div><Checkbox.Group value={topics} onChange={setTopics} options={selected.topics}/></section><section><div><strong>选择消费者</strong><span>{consumers.length} / {selected.consumers.length}</span></div><Checkbox.Group value={consumers} onChange={setConsumers} options={selected.consumers}/></section></div>
    <div className="copy-summary"><span>目标托管：{selected.hosting}</span><span>Runtime：{selected.runtimes} 个</span><span>Meta：{selected.metaNodes} 个</span></div>
  </Modal>;
}

export function MockClusterOverview() {
  const navigate=useNavigate(); const [query,setQuery]=useState(""); const [hosting,setHosting]=useState("all"); const [copyId,setCopyId]=useState(null);
  const {tasks:copyTasks,clusters,createCopyTask}=useCopyTasks();
  const filtered=clusters.filter((cluster)=>`${cluster.name} ${cluster.region} ${cluster.description}`.toLowerCase().includes(query.toLowerCase())&&(hosting==="all"||cluster.hostingType===hosting));
  const avg=(key)=>Math.round(clusters.reduce((sum,cluster)=>sum+cluster[key],0)/clusters.length);
  return <div className="page mock-cluster-page">
    <header className="mock-page-heading"><div><div><h1>集群</h1><MockTag/></div><p>查看全部 EventMesh 集群的托管环境、资源使用率与消息运行状态。</p></div><Button type="primary" icon={<CopyOutlined/>} onClick={()=>setCopyId(clusters[0].id)}>复制集群</Button></header>
    <section className="mock-summary-strip"><div><span>集群总数</span><strong>{clusters.length}</strong><small>{clusters.filter((item)=>item.status==="healthy").length} 个正常 · {clusters.filter((item)=>item.status==="warning").length} 个需关注 · {clusters.filter((item)=>item.status==="unknown").length} 个未知</small></div><div><span>Runtime 节点</span><strong>{clusters.reduce((sum,item)=>sum+item.runtimes,0)}</strong><small>分布在 {clusters.length} 个集群</small></div><div><span>平均 CPU</span><strong>{avg("cpu")}%</strong><small>集群资源使用率</small></div><div><span>平均内存</span><strong>{avg("memory")}%</strong><small>集群资源使用率</small></div><div><span>消息速率</span><strong>{formatRate(clusters.reduce((sum,item)=>sum+item.inRate,0))}</strong><small>总流入速率</small></div></section><CopyTaskPanel tasks={copyTasks}/>
    <section className="panel mock-cluster-table-panel"><div className="mock-table-toolbar"><div><h2>所有集群</h2><span>点击整行进入集群详情</span></div><div><Input prefix={<SearchOutlined/>} allowClear value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="搜索集群名称或地域"/><Select value={hosting} onChange={setHosting} options={[{value:"all",label:"全部托管方式"},{value:"Kubernetes",label:"Kubernetes"},{value:"主机集群",label:"主机集群"}]}/><Button icon={<ReloadOutlined/>}>刷新</Button></div></div>
      <div className="resource-table-wrap"><table className="resource-table mock-cluster-table"><thead><tr><th>集群</th><th>状态</th><th>托管方式</th><th>节点</th><th>资源使用率</th><th>MQ 速率</th><th>地域 / 版本</th><th>操作</th></tr></thead><tbody>{filtered.map((cluster)=>{const openCluster=()=>navigate(`/clusters/${cluster.id}/overview`);return <tr key={cluster.id} tabIndex={0} onClick={openCluster} onKeyDown={(event)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();openCluster();}}}><td><span className="mock-cluster-identity"><i><ClusterOutlined/></i><span><strong>{cluster.name}</strong><small>{cluster.description}</small></span></span></td><td><Status value={cluster.status}/></td><td><span className="hosting-cell"><strong>{cluster.hostingType}</strong><small>{cluster.hosting}</small><small>{cluster.kubernetes}</small></span></td><td><strong>{cluster.runtimes}</strong> Runtime<br/><small>{cluster.metaNodes} Meta</small></td><td><div className="compact-usage"><UsageBar label="CPU" value={cluster.cpu}/><UsageBar label="内存" value={cluster.memory}/></div></td><td><span className="rate-cell"><strong>入 {formatRate(cluster.inRate)}</strong><small>出 {formatRate(cluster.outRate)}</small></span></td><td><span className="hosting-cell"><strong>{cluster.region}</strong><small>v{cluster.version}</small></span></td><td><span className="row-action-buttons"><Button type="link" onClick={(event)=>{event.stopPropagation();openCluster();}}>管理</Button><Button type="link" icon={<CopyOutlined/>} onClick={(event)=>{event.stopPropagation();setCopyId(cluster.id);}}>复制</Button></span></td></tr>;})}</tbody></table>{!filtered.length&&<div className="mock-empty"><SearchOutlined/><strong>未找到匹配集群</strong><span>请调整搜索或托管方式筛选。</span></div>}</div>
    </section><ClusterCopyModal open={Boolean(copyId)} sourceId={copyId} onClose={()=>setCopyId(null)} onCreate={createCopyTask} clusters={clusters}/>
  </div>;
}

function MessageRateChart(){ const option=useMemo(()=>({animationDuration:500,color:["#225aa0","#4cb6d4"],tooltip:{trigger:"axis"},legend:{right:8,top:0,itemWidth:18,textStyle:{color:"#5f7388"},data:["流入","流出"]},grid:{left:50,right:22,top:42,bottom:32},xAxis:{type:"category",boundaryGap:false,data:mockMessageSeries.labels,axisLine:{lineStyle:{color:"#b9c9d9"}},axisLabel:{color:"#6b7e92"}},yAxis:{type:"value",name:"K 条/s",splitLine:{lineStyle:{color:"#e5edf5"}},axisLabel:{color:"#6b7e92"}},series:[{name:"流入",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},data:mockMessageSeries.inbound},{name:"流出",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},data:mockMessageSeries.outbound}]}),[]); return <ReactECharts option={option} style={{height:270}}/>; }
function RuntimeResourceChart(){ const option=useMemo(()=>({animationDuration:500,color:["#225aa0","#72869b"],tooltip:{trigger:"axis",valueFormatter:(value)=>`${value}%`},legend:{right:8,top:0,itemWidth:18,textStyle:{color:"#5f7388"},data:["CPU","内存"]},grid:{left:48,right:22,top:42,bottom:32},xAxis:{type:"category",boundaryGap:false,data:mockMessageSeries.labels,axisLine:{lineStyle:{color:"#b9c9d9"}},axisLabel:{color:"#6b7e92"}},yAxis:{type:"value",min:0,max:100,axisLabel:{formatter:"{value}%",color:"#6b7e92"},splitLine:{lineStyle:{color:"#e5edf5"}}},series:[{name:"CPU",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},areaStyle:{opacity:.05},data:[39,42,41,45,48,46,49,51,47,50,46,48]},{name:"内存",type:"line",smooth:true,symbol:"none",lineStyle:{width:2},data:[55,57,58,60,62,61,64,65,63,66,64,62]}]}),[]); return <ReactECharts option={option} style={{height:270}}/>; }
function MonitorTrendChart({series,unit}){ const option=useMemo(()=>({animationDuration:500,color:["#225aa0","#72869b","#4cb6d4"],tooltip:{trigger:"axis"},legend:{right:8,top:0,itemWidth:18,textStyle:{color:"#5f7388"},data:series.map((item)=>item.name)},grid:{left:50,right:22,top:42,bottom:32},xAxis:{type:"category",boundaryGap:false,data:mockMessageSeries.labels,axisLine:{lineStyle:{color:"#b9c9d9"}},axisLabel:{color:"#6b7e92"}},yAxis:{type:"value",name:unit,splitLine:{lineStyle:{color:"#e5edf5"}},axisLabel:{color:"#6b7e92"}},series:series.map((item,index)=>({...item,type:"line",smooth:true,symbol:"none",lineStyle:{width:2},areaStyle:index===0?{opacity:.05}:undefined}))}),[series,unit]); return <ReactECharts option={option} style={{height:270}}/>; }
function ModuleMonitoringOverview({title,description,kpis,charts,health}){
  return <div className="mock-runtime-monitoring"><section className="panel mock-monitor-summary"><div className="mock-section-title"><div><h2>{title}</h2><p>{description}</p></div><Select defaultValue="2h" options={[{value:"2h",label:"最近 2 小时"},{value:"24h",label:"最近 24 小时"}]}/></div><div className="mock-monitor-kpis">{kpis.map((item)=><span key={item.label}><small>{item.label}</small><strong>{item.value}</strong><em>{item.note}</em></span>)}</div></section><div className="mock-monitor-charts">{charts.map((chart)=><section className="panel" key={chart.title}><div className="mock-section-title"><div><h2>{chart.title}</h2><p>{chart.description}</p></div></div><MonitorTrendChart series={chart.series} unit={chart.unit}/></section>)}</div><section className="panel mock-monitor-health"><div className="mock-section-title"><div><h2>运行健康</h2><p>关键状态与需要关注的运行信号</p></div></div><div className="mock-health-cells">{health.map((item)=><span key={item.label} className={item.warning?"warning":""}>{item.warning?<ExclamationCircleOutlined/>:<CheckCircleOutlined/>}<small>{item.label}</small><strong>{item.value}</strong><em>{item.note}</em></span>)}</div></section></div>;
}
function RuntimeMonitoringOverview({cluster,runtimeNodes,metaNodes,onOpenNodes}){
  const average=(key)=>runtimeNodes.length?Math.round(runtimeNodes.reduce((sum,node)=>sum+Number(node[key]||0),0)/runtimeNodes.length):0;
  const healthy=runtimeNodes.filter((node)=>node.status==="正常").length;
  return <div className="mock-runtime-monitoring">
    <section className="panel mock-monitor-summary"><div className="mock-section-title"><div><h2>Runtime 监控概览</h2><p>节点资源、消息处理与服务质量的实时快照</p></div><Select defaultValue="2h" options={[{value:"2h",label:"最近 2 小时"},{value:"24h",label:"最近 24 小时"}]}/></div><div className="mock-monitor-kpis"><span><small>在线 Runtime</small><strong>{healthy} / {runtimeNodes.length}</strong><em>全部节点可用</em></span><span><small>平均 CPU</small><strong>{average("cpu")}%</strong><em>峰值 51%</em></span><span><small>平均内存</small><strong>{average("memory")}%</strong><em>峰值 67%</em></span><span><small>消息处理速率</small><strong>{formatRate(cluster.inRate)}</strong><em>较前一小时 +4.8%</em></span><span><small>P99 处理延迟</small><strong>38 ms</strong><em>目标 &lt; 80 ms</em></span></div></section>
    <div className="mock-monitor-charts"><section className="panel"><div className="mock-section-title"><div><h2>CPU 与内存趋势</h2><p>Runtime 节点平均资源使用率</p></div></div><RuntimeResourceChart/></section><section className="panel"><div className="mock-section-title"><div><h2>消息吞吐趋势</h2><p>集群流入与流出速率</p></div></div><MessageRateChart/></section></div>
    <section className="panel mock-monitor-health"><div className="mock-section-title"><div><h2>运行健康</h2><p>Runtime 与 Meta 关键运行状态</p></div><Button type="link" onClick={onOpenNodes}>查看 Runtime 节点</Button></div><div className="mock-health-cells"><span><CheckCircleOutlined/><small>Runtime 可用性</small><strong>100%</strong><em>{healthy} 个节点正常</em></span><span><CheckCircleOutlined/><small>Meta 仲裁</small><strong>{metaNodes.length} / {metaNodes.length}</strong><em>Leader 正常</em></span><span><CheckCircleOutlined/><small>请求成功率</small><strong>99.96%</strong><em>近 2 小时</em></span><span><ExclamationCircleOutlined/><small>活跃告警</small><strong>1</strong><em>消费积压需关注</em></span></div></section>
  </div>;
}
function AddNodeModal({open,onClose,onAdd}){ const {message}=AntApp.useApp(); const [role,setRole]=useState("Runtime"); const [name,setName]=useState("runtime-east-07"); const [spec,setSpec]=useState("4 vCPU / 8 GiB"); const submit=()=>{onAdd({name,role,address:"待分配",cpu:0,memory:0,rate:"0/s",status:"初始化中"});message.success(`节点 ${name} 已加入模拟集群`);onClose();}; return <Modal title="添加集群节点" open={open} onCancel={onClose} onOk={submit} okText="添加节点" cancelText="取消" okButtonProps={{disabled:!name.trim()}}><div className="mock-flow-note"><PlusOutlined/><div><strong>添加到当前集群</strong><span>节点将继承当前集群的托管环境与网络配置。</span></div></div><div className="add-node-form"><label>节点角色<Select value={role} onChange={(value)=>{setRole(value);setName(value==="Runtime"?"runtime-east-07":"meta-east-04");}} options={[{value:"Runtime",label:"Runtime 节点"},{value:"Meta",label:"Meta 节点"}]}/></label><label>节点名称<Input value={name} onChange={(event)=>setName(event.target.value)}/></label><label>资源规格<Select value={spec} onChange={setSpec} options={["2 vCPU / 4 GiB","4 vCPU / 8 GiB","8 vCPU / 16 GiB"].map((value)=>({value,label:value}))}/></label></div></Modal>; }

function ModuleTable({title,description,columns,rows,action=null}){
  return <section className="panel mock-tab-panel mock-module-panel"><div className="mock-section-title"><div><h2>{title}</h2><p>{description}</p></div>{action}</div><div className="resource-table-wrap"><table className="resource-table mock-module-table"><thead><tr>{columns.map((column)=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={`${title}-${index}`}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div></section>;
}

function buildMockTopology(cluster,runtimeNodes,metaNodes){
  const runtimeItems=runtimeNodes.map((node,index)=>({id:`runtime-${index+1}`,name:node.name,status:"Healthy",host:String(node.address).split(":")[0],port:10000,version:cluster.version}));
  const metaItems=metaNodes.map((node,index)=>({key:`meta-runtime-${index+1}`,id:`meta-${index+1}`,kind:"runtime",relation:"RUNTIME_MEMBER",name:node.name,status:"Healthy",host:String(node.address).split(":")[0],port:2379,version:"3.5.12"}));
  return {
    root:{key:`cluster-${cluster.id}`,id:cluster.id,kind:"cluster",relation:"ROOT",name:cluster.name,status:"Healthy",clusterType:"EVENTMESH_CLUSTER",version:cluster.version,description:cluster.description,children:[
      {key:`cluster-${cluster.id}-meta`,id:`${cluster.id}-meta`,kind:"cluster",relation:"CLUSTER_RELATIONSHIP",name:`${cluster.name}-meta`,status:"Healthy",clusterType:"META_CLUSTER",version:"3.5.12",children:metaItems},
      {key:`cluster-${cluster.id}-store`,id:`${cluster.id}-store`,kind:"cluster",relation:"CLUSTER_RELATIONSHIP",name:`${cluster.name}-rocketmq`,status:"Healthy",clusterType:"STORAGE_ROCKETMQ_CLUSTER",version:"5.3.1",children:[]},
    ]},
    runtimes:runtimeItems,
  };
}

export function MockClusterDetail(){
  const navigate=useNavigate();
  const location=useLocation();
  const {clusterId,view}=useParams();
  const {tasks:copyTasks,clusters,createCopyTask}=useCopyTasks();
  const cluster=clusters.find((item)=>item.id===clusterId)??clusters[0];
  const allowedViews=["overview","runtime","topics","connections","consumers","operations","messages","security","topology"];
  const activeView=allowedViews.includes(view)?view:"overview";
  const showClusterHeader=activeView==="overview"||activeView==="topology";
  useEffect(()=>{ if(view&&!allowedViews.includes(view)) navigate(`/clusters/${cluster.id}/overview`,{replace:true}); },[view,cluster.id,navigate]);
  const [copyOpen,setCopyOpen]=useState(false); const [addOpen,setAddOpen]=useState(false);
  const startCopyTask=(task)=>{ createCopyTask(task); navigate(`/clusters/${cluster.id}/overview`); };
  const [runtimeNodes,setRuntimeNodes]=useState(mockRuntimeNodes.slice(0,cluster.runtimes)); const [metaNodes,setMetaNodes]=useState(mockMetaNodes.slice(0,cluster.metaNodes));
  const addNode=(node)=>node.role==="Meta"?setMetaNodes((current)=>[...current,{...node,role:"Follower",latency:"—"}]):setRuntimeNodes((current)=>[...current,node]);
  const topologyData=useMemo(()=>buildMockTopology(cluster,runtimeNodes,metaNodes),[cluster,runtimeNodes,metaNodes]);
  const topologyTopics=cluster.topics.map((name,index)=>({id:index+1,topicName:name,topicType:"NORMAL",readQueueNum:12,writeQueueNum:12,status:"Healthy"}));
  const topologyGroups=cluster.consumers.map((name,index)=>({id:index+1,name,type:0,state:"ONLINE",status:"Healthy"}));
  const detailSection=new URLSearchParams(location.search).get("section")||"overview";
  const overview=<div className="mock-overview-grid"><section className="panel mock-hosting-panel"><div className="mock-section-title"><div><h2>托管与资源</h2><p>当前集群运行基础与容量水位</p></div><CloudServerOutlined/></div><dl><div><dt>托管方式</dt><dd>{cluster.hosting}</dd></div><div><dt>基础设施</dt><dd>{cluster.hostingType}</dd></div><div><dt>K8s 集群</dt><dd>{cluster.kubernetes}</dd></div><div><dt>节点规模</dt><dd>{runtimeNodes.length} Runtime · {metaNodes.length} Meta</dd></div></dl><div className="mock-usage-stack"><UsageBar label="CPU" value={cluster.cpu}/><UsageBar label="内存" value={cluster.memory}/><UsageBar label="存储" value={cluster.storage}/></div></section><section className="panel mock-runtime-summary"><div className="mock-section-title"><div><h2>Runtime 集群</h2><p>消息接入与路由节点</p></div><ClusterOutlined/></div><strong>{runtimeNodes.length}</strong><span>个 Runtime 节点</span><div><small>正常节点</small><b>{runtimeNodes.filter((node)=>node.status==="正常").length}</b></div><div><small>平均 CPU</small><b>{cluster.cpu}%</b></div><Button type="link" onClick={()=>navigate(`/clusters/${cluster.id}/runtime`)}>查看 Runtime</Button></section><section className="panel mock-runtime-summary"><div className="mock-section-title"><div><h2>Meta 集群</h2><p>注册与元数据协调</p></div><DatabaseOutlined/></div><strong>{metaNodes.length}</strong><span>个 Meta 节点</span><div><small>Leader</small><b>1</b></div><div><small>平均延迟</small><b>8 ms</b></div><Button type="link" onClick={()=>navigate(`/clusters/${cluster.id}/topology`)}>查看拓扑</Button></section><section className="panel mock-chart-panel"><div className="mock-section-title"><div><h2>MQ 消费情况与速率</h2><p>最近 2 小时消息流入与消费速率</p></div><Select defaultValue="2h" options={[{value:"2h",label:"最近 2 小时"},{value:"24h",label:"最近 24 小时"}]}/></div><div className="mock-rate-kpis"><span><small>流入速率</small><strong>{formatRate(cluster.inRate)}</strong></span><span><small>消费速率</small><strong>{formatRate(cluster.outRate)}</strong></span><span><small>消费积压</small><strong>12.6K</strong></span><span><small>平均延迟</small><strong>38 ms</strong></span></div><MessageRateChart/></section><section className="panel mock-resource-table"><div className="mock-section-title"><div><h2>消息资源</h2><p>Topic 与消费者运行概览</p></div><TeamOutlined/></div><table><thead><tr><th>资源类型</th><th>数量</th><th>活跃</th><th>消息速率</th><th>积压</th></tr></thead><tbody><tr><td>Topic</td><td>{cluster.topics.length}</td><td>{cluster.topics.length}</td><td>{formatRate(cluster.inRate)}</td><td>—</td></tr><tr><td>消费者</td><td>{cluster.consumers.length}</td><td>{cluster.consumers.length}</td><td>{formatRate(cluster.outRate)}</td><td>12.6K</td></tr></tbody></table></section></div>;
  const views={
    overview,
    runtime:detailSection==="runtime"?<ModuleTable title="Runtime / Broker 节点" description="消息接入、路由与协议处理实例" columns={["节点名称","地址","CPU / 内存","消息速率","状态","操作"]} rows={runtimeNodes.map((node)=>[<strong>{node.name}</strong>,node.address,`${node.cpu}% / ${node.memory}%`,node.rate,<span className="mock-status healthy"><CheckCircleOutlined/>正常</span>,<Button type="link">查看</Button>])} action={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setAddOpen(true)}>添加节点</Button>}/>:detailSection==="meta"?<ModuleTable title="Meta 节点" description="注册、发现与元数据协调节点" columns={["节点名称","角色","地址","延迟","状态"]} rows={metaNodes.map((node)=>[<strong>{node.name}</strong>,node.role,node.address,node.latency,<span className="mock-status healthy"><CheckCircleOutlined/>正常</span>])} action={<Button type="primary" icon={<PlusOutlined/>} onClick={()=>setAddOpen(true)}>添加节点</Button>}/>:<RuntimeMonitoringOverview cluster={cluster} runtimeNodes={runtimeNodes} metaNodes={metaNodes} onOpenNodes={()=>navigate(`/clusters/${cluster.id}/runtime?section=runtime`)}/>,
    topics:detailSection==="list"?<ModuleTable title="Topic 列表" description="当前集群的主题与分区运行状态" columns={["Topic 名称","分区","副本","流入速率","流出速率","状态"]} rows={cluster.topics.map((name,index)=>[<strong>{name}</strong>,index%2?8:12,3,`${(12.8-index*1.4).toFixed(1)}K/s`,`${(10.6-index).toFixed(1)}K/s`,<span className="mock-status healthy"><CheckCircleOutlined/>正常</span>])}/>:<ModuleMonitoringOverview title="Topic 监控概览" description="主题可用性、分区负载与消息吞吐" kpis={[{label:"Topic 总数",value:cluster.topics.length,note:"全部可用"},{label:"分区总数",value:52,note:"无离线分区"},{label:"流入速率",value:formatRate(cluster.inRate),note:"较前一小时 +4.8%"},{label:"流出速率",value:formatRate(cluster.outRate),note:"消费保持稳定"},{label:"消息存储",value:"1.84 TB",note:"使用率 38%"}]} charts={[{title:"Topic 吞吐趋势",description:"全部 Topic 流入与流出速率",unit:"K 条/s",series:[{name:"流入",data:mockMessageSeries.inbound},{name:"流出",data:mockMessageSeries.outbound}]},{title:"分区负载趋势",description:"分区写入与读取负载",unit:"%",series:[{name:"写入负载",data:[38,42,45,43,48,51,49,54,52,57,55,58]},{name:"读取负载",data:[31,34,36,38,40,39,43,45,44,48,47,49]}]}]} health={[{label:"可用 Topic",value:`${cluster.topics.length} / ${cluster.topics.length}`,note:"全部正常"},{label:"离线分区",value:"0",note:"无异常"},{label:"副本不足",value:"0",note:"副本同步正常"},{label:"热点 Topic",value:"1",note:"order-created 接近阈值",warning:true}]}/>,
    connections:detailSection==="list"?<ModuleTable title="连接列表" description="客户端到 Runtime 的活跃连接" columns={["客户端","协议","Runtime","连接数","最近活动","状态"]} rows={[["order-gateway","HTTP","runtime-east-01",238,"刚刚"],["payment-adapter","TCP","runtime-east-02",164,"3 秒前"],["inventory-connector","MQTT","runtime-east-03",92,"7 秒前"]].map((row)=>[...row,<span className="mock-status healthy"><CheckCircleOutlined/>在线</span>])}/>:<ModuleMonitoringOverview title="连接监控概览" description="客户端连接规模、稳定性与协议运行状态" kpis={[{label:"活跃连接",value:"12.4K",note:"分布在 6 个 Runtime"},{label:"每秒新建",value:"186/s",note:"较前一小时 +2.1%"},{label:"每秒断开",value:"14/s",note:"处于正常区间"},{label:"连接失败率",value:"0.04%",note:"目标 < 0.1%"},{label:"活跃协议",value:"3",note:"HTTP · TCP · MQTT"}]} charts={[{title:"连接数量趋势",description:"活跃连接与新建连接",unit:"连接数",series:[{name:"活跃连接",data:[10.8,11.1,11.3,11.5,11.8,11.7,12.0,12.2,12.1,12.3,12.2,12.4]},{name:"新建连接",data:[142,151,148,160,172,168,178,181,176,184,179,186]}]},{title:"连接稳定性",description:"断开与失败连接变化",unit:"次/s",series:[{name:"断开",data:[11,12,10,14,13,12,15,14,13,15,14,14]},{name:"失败",data:[2,1,2,2,3,2,2,3,2,2,1,2]}]}]} health={[{label:"在线 Runtime",value:`${runtimeNodes.length} / ${runtimeNodes.length}`,note:"均可接受连接"},{label:"连接成功率",value:"99.96%",note:"近 2 小时"},{label:"空闲连接占比",value:"8.2%",note:"处于正常范围"},{label:"异常客户端",value:"0",note:"未发现持续重连"}]}/>,
    consumers:<ModuleTable title="Consumer" description="消费者组、积压与消费速率" columns={["消费者组","订阅 Topic","实例","消费速率","积压","状态"]} rows={cluster.consumers.map((name,index)=>[<strong>{name}</strong>,cluster.topics[index%cluster.topics.length],index+2,`${(18.2-index*2.1).toFixed(1)}K/s`,index===1?"8.4K":"1.2K",<span className={`mock-status ${index===1?"warning":"healthy"}`}>{index===1?<ExclamationCircleOutlined/>:<CheckCircleOutlined/>}{index===1?"需关注":"正常"}</span>])}/>,
    operations:<ModuleTable title="操作历史" description="集群运维操作与复制任务执行记录" columns={["时间","操作","资源","操作者","结果"]} rows={[...copyTasks.map((task)=>[new Date(task.createdAt).toLocaleTimeString("zh-CN",{hour12:false}),"复制集群",`${task.sourceName} → ${task.targetName}`,"admin",<span className={`mock-status ${task.progress>=100?"healthy":"warning"}`}>{task.progress>=100?<CheckCircleOutlined/>:<ReloadOutlined spin/>}{task.progress>=100?"成功":`${copyTaskPhase(task.progress)} ${task.progress}%`}</span>]),...[["10:42:18","更新配置",cluster.name,"admin"],["09:17:52","创建 Topic","order-created","ops-user"],["08:55:11","扩容 Runtime","runtime-east-06","admin"]].map((row)=>[...row,<span className="mock-status healthy"><CheckCircleOutlined/>成功</span>]) ]}/>,
    messages:<section className="panel mock-tab-panel"><div className="mock-section-title"><div><h2>Message</h2><p>MQ 流入、消费速率与积压趋势</p></div><HddOutlined/></div><div className="mock-rate-kpis wide"><span><small>Topic</small><strong>{cluster.topics.length}</strong></span><span><small>消费者</small><strong>{cluster.consumers.length}</strong></span><span><small>流入速率</small><strong>{formatRate(cluster.inRate)}</strong></span><span><small>消费速率</small><strong>{formatRate(cluster.outRate)}</strong></span></div><MessageRateChart/></section>,
    security:<ModuleTable title="Security" description="集群安全策略与访问控制（模拟配置）" columns={["策略","范围","状态","最近更新"]} rows={[["TLS 传输加密","全部 Runtime","已启用","2026-08-18 09:30"],["Topic ACL","生产 Topic","已启用","2026-08-17 16:12"],["管理网络白名单","10.18.0.0/16","已启用","2026-08-16 11:05"]].map((row)=>[row[0],row[1],<span className="mock-status healthy"><CheckCircleOutlined/>{row[2]}</span>,row[3]])}/>,
    topology:<div className="mock-topology-view"><TopologyExperience cluster={{...cluster,clusterId:cluster.id,clusterType:"EVENTMESH_CLUSTER",status:"Healthy"}} topology={topologyData.root} runtimes={topologyData.runtimes} topics={topologyTopics} groups={topologyGroups} error={null} loading={false} fetching={false} fetchedAt={new Date().toISOString()} onRefresh={()=>{}} onExit={()=>navigate(`/clusters/${cluster.id}/overview`)}/></div>,
  };
  return <div className="page mock-cluster-detail">{showClusterHeader&&<><section className="mock-detail-hero"><div><button onClick={()=>navigate("/clusters")}>全部集群 /</button><div className="mock-detail-title"><h1>{cluster.name}</h1><Status value={cluster.status}/><MockTag/></div><p>{cluster.description}</p><div className="mock-detail-meta"><span>版本 {cluster.version}</span><span>{cluster.region}</span><span>运行 {cluster.uptime}</span><span>集群 ID {cluster.id}</span></div></div><div className="mock-detail-actions"><Button icon={<CopyOutlined/>} onClick={()=>setCopyOpen(true)}>复制集群</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setAddOpen(true)}>添加节点</Button></div></section>{activeView==="overview"&&<CopyTaskPanel tasks={copyTasks}/>}<div className="mock-cluster-view-heading"><strong>{activeView==="overview"?"Cluster 概要":"集群拓扑"}</strong><span>当前集群 · {cluster.name}</span></div></>}{views[activeView]}<ClusterCopyModal open={copyOpen} sourceId={cluster.id} onClose={()=>setCopyOpen(false)} onCreate={startCopyTask} clusters={clusters}/><AddNodeModal open={addOpen} onClose={()=>setAddOpen(false)} onAdd={addNode}/></div>;
}
