<template><section class="panel topology-shell"><div class="topology-main"><div class="topology-toolbar"><t-radio-group v-model="mode" variant="default-filled"><t-radio-button value="graph">关系图</t-radio-button><t-radio-button value="tree">资源树</t-radio-button></t-radio-group><t-input v-model="search" clearable placeholder="搜索名称、ID 或地址" /></div><div v-if="mode === 'graph'" ref="host" class="topology-canvas" /><div v-else class="tree-stage"><t-tree :data="treeData" activable hover expand-all :filter="filter" @active="selectTree" /></div><t-alert v-if="error" theme="warning" title="拓扑渲染失败" :message="error.message" /></div><aside class="inspector"><template v-if="selected"><StatusBadge :value="selected.status" :label="selected.status === 'healthy' ? '正常' : '需关注'"/><h2>{{ selected.label }}</h2><p>{{ selected.type }}</p><dl><div v-for="(value,key) in selected" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl></template><PageState v-else type="empty" title="选择节点查看详情" description="关系图和资源树共享当前选择。" /></aside></section></template>
<script setup lang="ts">
import { computed, ref, watch } from "vue"; import { useRoute, useRouter } from "vue-router"; import { useTopologyGraph } from "../composables/useTopologyGraph"; import StatusBadge from "../components/common/StatusBadge.vue"; import PageState from "../components/common/PageState.vue";
const props = defineProps<{ cluster: any; components: any[]; runtimes?: any[]; topics?: any[]; groups?: any[] }>(); const route = useRoute(); const router = useRouter(); const host = ref<HTMLElement|null>(null); const search = ref(String(route.query.q ?? "")); const mode = ref(route.query.mode === "tree" ? "tree" : "graph"); const selected = ref<any>(null);
const nodes = computed(() => { const root = { id:`eventmesh-${props.cluster.id}`, data:{ id:`eventmesh-${props.cluster.id}`, label:props.cluster.name, type:"EventMesh",status:"healthy" } }; const children = (props.components??[]).map((item:any)=>({ id:`component-${item.id}`, data:{ id:`component-${item.id}`, label:item.name, type:item.type,status:item.status??"healthy",version:item.version??"—",region:item.region??"—" } })); const runtimes=(props.runtimes??[]).slice(0,8).map((item:any)=>({id:`runtime-${item.id??item.name}`,data:{id:`runtime-${item.id??item.name}`,label:item.name??item.id,type:"Runtime",status:item.status??"healthy",address:item.address??item.host??"—"}})); return [root,...children,...runtimes]; });
const graphData = computed(() => ({ nodes: nodes.value, edges: nodes.value.slice(1).map((node:any)=>({source:`eventmesh-${props.cluster.id}`,target:node.id,data:{color:node.data.type==="Runtime"?"#4cb6d4":"#225aa0"}})) }));
function choose(node:any){ selected.value=node; router.replace({query:{...route.query,node:node.id}}); } const {error}=useTopologyGraph(host,graphData,choose);
const treeData = computed(()=>[{value:`eventmesh-${props.cluster.id}`,label:props.cluster.name,children:[{value:"components",label:"关联组件（真实拓扑）",children:(props.components??[]).map((item:any)=>({value:`component-${item.id}`,label:item.name,data:{...item,label:item.name}}))},{value:"runtime-directory",label:"Runtime 资源目录（非拓扑关系）",children:(props.runtimes??[]).map((item:any)=>({value:`runtime-${item.id??item.name}`,label:item.name??item.id,data:{...item,label:item.name??item.id,type:"Runtime"}}))},{value:"topic-directory",label:"Topic 资源目录（非拓扑关系）",children:(props.topics??[]).map((item:any)=>({value:`topic-${item.id??item.name}`,label:item.name??item.topicName,data:{...item,label:item.name??item.topicName,type:"Topic"}}))}]}]);
const filter = computed(() => search.value ? ((node:any)=>String(node.label).toLowerCase().includes(search.value.toLowerCase())) : undefined); function selectTree(values:any[],ctx:any){ const node=ctx?.node?.data??ctx?.node; if(node) choose({id:node.value,...node.data,label:node.label,status:node.data?.status??"unknown"}); }
watch([mode,search],()=>router.replace({query:{...route.query,mode:mode.value==="tree"?"tree":undefined,q:search.value||undefined}}));
</script>
<style scoped>.tree-stage{height:540px;overflow:auto;padding:18px}.topology-canvas :deep(canvas){display:block}</style>
